### ISSUE TITLE
Disappearing Mobs

### ISSUE THREAD

**Issue by alex6777** [PaperMC/Folia#117]
### Stack trace

```
java.lang.IllegalStateException: Scheduling chunk load off-main
	at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:72) ~[folia-1.20.1.jar:git-Folia-"6b978f2"]
	at net.minecraft.server.level.ServerChunkCache.getChunkFutureMainThread(ServerChunkCache.java:311) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.getChunk(ServerChunkCache.java:239) ~[?:?]
	at net.minecraft.world.level.Level.getChunk(Level.java:524) ~[?:?]
	at net.minecraft.world.level.Level.getBlockState(Level.java:821) ~[?:?]
	at net.minecraft.world.entity.ai.navigation.GroundPathNavigation.createPath(GroundPathNavigation.java:43) ~[?:?]
	at net.minecraft.world.entity.ai.navigation.PathNavigation.createPath(PathNavigation.java:114) ~[?:?]
	at net.minecraft.world.entity.ai.behavior.MoveToTargetSink.tryComputePath(MoveToTargetSink.java:110) ~[?:?]
	at net.minecraft.world.entity.ai.behavior.MoveToTargetSink.tick(MoveToTargetSink.java:100) ~[?:?]
	at net.minecraft.world.entity.ai.behavior.MoveToTargetSink.canStillUse(MoveToTargetSink.java:29) ~[?:?]
	at net.minecraft.world.entity.ai.behavior.Behavior.tickOrStop(Behavior.java:77) ~[folia-1.20.1.jar:git-Folia-"6b978f2"]
	at net.minecraft.world.entity.ai.Brain.tickEachRunningBehavior(Brain.java:453) ~[?:?]
	at net.minecraft.world.entity.ai.Brain.tick(Brain.java:390) ~[?:?]
	at net.minecraft.world.entity.animal.sniffer.Sniffer.customServerAiStep(Sniffer.java:496) ~[folia-1.20.1.jar:git-Folia-"6b978f2"]
	at net.minecraft.world.entity.Mob.serverAiStep(Mob.java:946) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3371) ~[?:?]
	at net.minecraft.world.entity.Mob.aiStep(Mob.java:693) ~[?:?]
	at net.minecraft.world.entity.AgeableMob.aiStep(AgeableMob.java:155) ~[?:?]
	at net.minecraft.world.entity.animal.Animal.aiStep(Animal.java:61) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3026) ~[?:?]
	at net.minecraft.world.entity.Mob.tick(Mob.java:455) ~[?:?]
	at net.minecraft.world.entity.animal.sniffer.Sniffer.tick(Sniffer.java:383) ~[folia-1.20.1.jar:git-Folia-"6b978f2"]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1371) ~[?:?]
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:958) ~[?:?]
	at net.minecraft.server.level.ServerLevel.lambda$tick$12(ServerLevel.java:848) ~[?:?]
	at io.papermc.paper.threadedregions.RegionizedWorldData.forEachTickingEntity(RegionizedWorldData.java:543) ~[folia-1.20.1.jar:git-Folia-"6b978f2"]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:827) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1676) ~[folia-1.20.1.jar:git-Folia-"6b978f2"]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:492) ~[folia-1.20.1.jar:git-Folia-"6b978f2"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1533) ~[folia-1.20.1.jar:git-Folia-"6b978f2"]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:367) ~[folia-1.20.1.jar:git-Folia-"6b978f2"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[folia-1.20.1.jar:git-Folia-"6b978f2"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.1.jar:git-Folia-"6b978f2"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Plugin and Datapack List

None

### Actions to reproduce (if known)

Unsure how to reproduce

### Folia version

This server is running Folia version git-Folia-"6b978f2" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: https://github.com/PaperMC/Folia/commit/6b978f2aafd9dd3d18a4ec2f1f5e28777763b3c7)
You are running the latest version
Previous version: git-Folia-"34039e3" (MC: 1.20.1)

**Comment by kugge** [comment]
Also happens on go to hive goal

```
- [mer. 23:10:02 ERROR Server] Entity threw exception at world_nether:-97.87349335637828,132.06164135048164,-139.5
java.lang.IllegalStateException: Scheduling chunk load off-main
    at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:76)
    at net.minecraft.server.level.ServerChunkCache.getChunkFutureMainThread(ServerChunkCache.java:311)
    at net.minecraft.server.level.ServerChunkCache.getChunk(ServerChunkCache.java:239)
    at net.minecraft.world.level.Level.getChunk(Level.java:612)
    at net.minecraft.world.level.Level.getBlockState(Level.java:909)
    at net.minecraft.world.entity.animal.Bee$BeeGoToHiveGoal.canBeeUse(Bee.java:1035)
    at net.minecraft.world.entity.animal.Bee$BaseBeeGoal.canUse(Bee.java:1365)
    at net.minecraft.world.entity.animal.Bee$BeeGoToHiveGoal.canUse(Bee.java:1014)
    at net.minecraft.world.entity.ai.goal.WrappedGoal.canUse(WrappedGoal.java:22)
    at net.minecraft.world.entity.ai.goal.GoalSelector.tick(GoalSelector.java:128)
    at net.minecraft.world.entity.Mob.serverAiStep(Mob.java:938)
    at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3371)
    at net.minecraft.world.entity.Mob.aiStep(Mob.java:693)
    at net.minecraft.world.entity.AgeableMob.aiStep(AgeableMob.java:155)
    at net.minecraft.world.entity.animal.Animal.aiStep(Animal.java:61)
    at net.minecraft.world.entity.animal.Bee.aiStep(Bee.java:487)
    at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3026)
    at net.minecraft.world.entity.Mob.tick(Mob.java:455)
    at net.minecraft.world.entity.animal.Bee.tick(Bee.java:274)
    at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1380)
    at net.minecraft.world.level.Level.guardEntityTick(Level.java:1046)
    at net.minecraft.server.level.ServerLevel.lambda$tick$12(ServerLevel.java:856)
    at io.papermc.paper.threadedregions.RegionizedWorldData.forEachTickingEntity(RegionizedWorldData.java:544)
    at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:828)
```

**Comment by Spottedleaf** [comment]
Fixed by https://github.com/PaperMC/Folia/commit/09ac612b2fd0677e77611b8c22ec60d9696e3866 https://github.com/PaperMC/Folia/commit/bd72070fb9b1916b84a0cc489dc87ac6e5ef4b52 https://github.com/PaperMC/Folia/commit/9ae65d1b3e4f23e46fb65546276ff091ffeac951
