### ISSUE TITLE
Cannot invoke "net.minecraft.world.entity.Entity.dH()" because "entity" is null

### ISSUE THREAD

**Issue by ewof** [PaperMC/Folia#126]
### Stack trace

```
[13:43:18 ERROR]: [io.papermc.paper.threadedregions.TickRegionScheduler] Region #1269 centered at chunk [394, -851] in world 'world' failed to tick:
net.minecraft.ReportedException: Exception ticking world
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1695) ~[folia-1.20.1.jar:git-Folia-"6b978f2"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[folia-1.20.1.jar:git-Folia-"6b978f2"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1533) ~[folia-1.20.1.jar:git-Folia-"6b978f2"]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:360) ~[folia-1.20.1.jar:git-Folia-"6b978f2"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[folia-1.20.1.jar:git-Folia-"6b978f2"
]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.1.jar:git-Folia-"6b978f2"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.Entity.dH()" because "entity" is null
        at io.papermc.paper.chunk.system.entity.EntityLookup.getEntityStatus(EntityLookup.java:375) ~[folia-1.20.1.jar:git-Folia-"6b978f2"]
        at io.papermc.paper.world.ChunkEntitySlices.updateStatus(ChunkEntitySlices.java:191) ~[folia-1.20.1.jar:?]
        at io.papermc.paper.chunk.system.entity.EntityLookup.chunkStatusChange(EntityLookup.java:316) ~[folia-1.20.1.jar:git-Folia-"6b978f2"]
        at io.papermc.paper.chunk.system.scheduling.NewChunkHolder.changeEntityChunkStatus(NewChunkHolder.java:1263) ~[folia-1.20.1.jar:git-Folia-"6b978f2"]
        at io.papermc.paper.chunk.system.scheduling.NewChunkHolder.handleFullStatusChange(NewChunkHolder.java:1372) ~[folia-1.20.1.jar:git-Folia-"6b978f2"]
        at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processPendingFullUpdate(ChunkHolderManager.java:1543) ~[folia-1.20.1.jar:git-Folia-"6b978
f2"]
        at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1521) ~[folia-1.20.1.jar:git-Folia-"6b978f2"]
        at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1474) ~[folia-1.20.1.jar:git-Folia-"6b978f2"]
        at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.tick(ChunkHolderManager.java:905) ~[folia-1.20.1.jar:git-Folia-"6b978f2"]
        at net.minecraft.server.level.DistanceManager.purgeStaleTickets(DistanceManager.java:63) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:442) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:793) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1676) ~[folia-1.20.1.jar:git-Folia-"6b978f2"]
        ... 6 more
```

### Plugin and Datapack List

```
> pl
[13:51:03 INFO]: Server Plugins (45):
[13:51:03 INFO]: Bukkit Plugins:
[13:51:03 INFO]:  - AnnouncerPlus, BattleScheduler, BetterRTP, BigDoors, Brewery, ChatControlRed, ChestShop, Chunky, ChunkyBorder, CoreProtect
[13:51:03 INFO]:  EventWar, FarmControl, FreedomChat, GrimAC, HexNicks, iConomy, InventoryRollbackPlus, InvSeePlusPlus, InvSeePlusPlus_Clear, InvS
eePlusPlus_Give
[13:51:03 INFO]:  LiteBans, LuckPerms, MapTowny, MvndiCore, MvndiCrafting, MvndiGUIShop, MvndiHunters, MvndiSiege, MvndiSpawning, MvndiUtils-Comba
t
[13:51:03 INFO]:  MvndiUtils-CombatSounds, MvndiUtils-Core, MvndiUtils-Equipment, MvndiUtils-Player, PlaceholderAPI, ProtocolLib, SiegeWeaponRemov
er, spark, squaremap, SuperVanish
[13:51:03 INFO]:  TAB, Towny, TownyBlockGlitch, TownyChat, Vault
```
no datapacks

### Actions to reproduce (if known)

nothing just walking around, very inconsistent happens sometimes doesn't happen sometimes

### Folia version

```
> version
[13:50:52 INFO]: Checking version, please wait...
[13:50:52 INFO]: This server is running Folia version git-Folia-"6b978f2" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 6b978
f2)
You are running the latest version
```

### Other
the chunk it's centered around and region # is different every time
happens on paper too
```
[05:14:16 ERROR]: Encountered an unexpected exception
net.minecraft.ReportedException: Exception ticking world
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1576) ~[paper-1.20.1.jar:git-Paper-65]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.1.jar:git-Paper-65]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1394) ~[paper-1.20.1.jar:git-Paper-65]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.1.jar:git-Paper-65]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-65]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.Entity.dH()" because "entity" is null
        at io.papermc.paper.chunk.system.entity.EntityLookup.getEntityStatus(EntityLookup.java:336) ~[paper-1.20.1.jar:git-Paper-65]
        at io.papermc.paper.world.ChunkEntitySlices.updateStatus(ChunkEntitySlices.java:191) ~[paper-1.20.1.jar:?]
        at io.papermc.paper.chunk.system.entity.EntityLookup.chunkStatusChange(EntityLookup.java:310) ~[paper-1.20.1.jar:git-Paper-65]
        at io.papermc.paper.chunk.system.scheduling.NewChunkHolder.changeEntityChunkStatus(NewChunkHolder.java:1263) ~[paper-1.20.1.jar:git-Paper-65]
        at io.papermc.paper.chunk.system.scheduling.NewChunkHolder.handleFullStatusChange(NewChunkHolder.java:1372) ~[paper-1.20.1.jar:git-Paper-65]
        at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processPendingFullUpdate(ChunkHolderManager.java:1382) ~[paper-1.20.1.jar:git-Paper-65]
        at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1366) ~[paper-1.20.1.jar:git-Paper-65]
        at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1319) ~[paper-1.20.1.jar:git-Paper-65]
        at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.tick(ChunkHolderManager.java:783) ~[paper-1.20.1.jar:git-Paper-65]
        at net.minecraft.server.level.DistanceManager.purgeStaleTickets(DistanceManager.java:63) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:492) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:827) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1557) ~[paper-1.20.1.jar:git-Paper-65]
        ... 5 more
[05:14:16 ERROR]:       Cause of unexpected exception was
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.Entity.dH()" because "entity" is null
        at io.papermc.paper.chunk.system.entity.EntityLookup.getEntityStatus(EntityLookup.java:336) ~[paper-1.20.1.jar:git-Paper-65]
        at io.papermc.paper.world.ChunkEntitySlices.updateStatus(ChunkEntitySlices.java:191) ~[paper-1.20.1.jar:?]
        at io.papermc.paper.chunk.system.entity.EntityLookup.chunkStatusChange(EntityLookup.java:310) ~[paper-1.20.1.jar:git-Paper-65]
        at io.papermc.paper.chunk.system.scheduling.NewChunkHolder.changeEntityChunkStatus(NewChunkHolder.java:1263) ~[paper-1.20.1.jar:git-Paper-65]
        at io.papermc.paper.chunk.system.scheduling.NewChunkHolder.handleFullStatusChange(NewChunkHolder.java:1372) ~[paper-1.20.1.jar:git-Paper-65]
        at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processPendingFullUpdate(ChunkHolderManager.java:1382) ~[paper-1.20.1.jar:git-Paper-65]
        at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1366) ~[paper-1.20.1.jar:git-Paper-65]
        at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1319) ~[paper-1.20.1.jar:git-Paper-65]
        at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.tick(ChunkHolderManager.java:783) ~[paper-1.20.1.jar:git-Paper-65]
        at net.minecraft.server.level.DistanceManager.purgeStaleTickets(DistanceManager.java:63) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:492) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:827) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1557) ~[paper-1.20.1.jar:git-Paper-65]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.1.jar:git-Paper-65]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1394) ~[paper-1.20.1.jar:git-Paper-65]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.1.jar:git-Paper-65]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-65]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[05:14:16 ERROR]: This crash report has been saved to: /mnt/ssd/mvndicraft/servers/dev_paper/./crash-reports/crash-2023-07-06_05.14.16-server.txt
```

**Comment by ewof** [comment]
running server on commit 801cff1 prevents these crashes

**Comment by ewof** [comment]
nvm happens on both commits

**Comment by ewof** [comment]
was a towny thing, fixed by lldm
