### ISSUE TITLE
Accessing entity state off owning region's thread (Teleport ArmorStand)

### ISSUE THREAD

**Issue by KonusIntelliJ** [PaperMC/Folia#132]
### Is your feature request related to a problem?

When i will teleport player with armorstand to location, then i will get exception (java.lang.IllegalStateException: Accessing entity state off owning region's thread)
How i can fix that?

log:
[HawkTab] Location task for HawkTab v1.0.0 in world CraftWorld{name=world} at -1, -1 generated an exception
java.lang.IllegalStateException: Accessing entity state off owning region's thread
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:79) ~[folia-1.20.1.jar:git-Folia-"34039e3"]
        at org.bukkit.craftbukkit.v1_20_R1.entity.CraftArmorStand.getHandle(CraftArmorStand.java:38) ~[folia-1.20.1.jar:git-Folia-"34039e3"]
        at org.bukkit.craftbukkit.v1_20_R1.entity.CraftArmorStand.getHandle(CraftArmorStand.java:13) ~[folia-1.20.1.jar:git-Folia-"34039e3"]
        at org.bukkit.craftbukkit.v1_20_R1.entity.CraftEntity.setSneaking(CraftEntity.java:1219) ~[folia-1.20.1.jar:git-Folia-"34039e3"]
        at net.hothawk.hawktab.listener.TabListener.lambda$onJoin$9(TabListener.java:131) ~[HawkTab-1.0.0-all.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaRegionScheduler$LocationScheduledTask.run(FoliaRegionScheduler.java:329) ~[folia-1.20.1.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaRegionScheduler$Scheduler.tick(FoliaRegionScheduler.java:270) ~[folia-1.20.1.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaRegionScheduler.tick(FoliaRegionScheduler.java:143) ~[folia-1.20.1.jar:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1515) ~[folia-1.20.1.jar:git-Folia-"34039e3"]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:360) ~[folia-1.20.1.jar:git-Folia-"34039e3"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[folia-1.20.1.jar:git-Folia-"34039e3"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.1.jar:git-Folia-"34039e3"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Describe the solution you'd like.

-

### Describe alternatives you've considered.

-

**Comment by electronicboy** [comment]
No code for us to say anything useful here, but, if you teleport an entity to somewhere else, you wanna modify it after its teleported, i.e. by using the future teleportAsync returns

**Comment by KonusIntelliJ** [comment]
Not need code, i want to hear what can this call. Thanks

> У нас нет кода, чтобы сказать здесь что-то полезное, но, если вы телепортируете сущность куда-то еще, вы хотите изменить ее после того, как она телепортируется, т.е. с помощью будущего телепортаАсинхронные возвращаются
