### ISSUE TITLE
Implement World (un)load API

### ISSUE THREAD

**Issue by kyngs** [PaperMC/Folia#134]
### Is your feature request related to a problem?

Yes, I need to load worlds on startup from my plugin

### Describe the solution you'd like.

Implement the current Bukkit API instead of throwing an exception

### Describe alternatives you've considered.

- Patch folia and hardcode the worlds I need
- Not to use folia

### Other

Thre's been a PR on this subject, but it was closed. I didn't find any issue tracking this matter.

**Comment by KonusIntelliJ** [comment]
I'm waiting too fix world API create/load

**Comment by maglink** [comment]
So, I'm uncommented "load world" function and it works perfectly. But I'm using it only on server startup. May be problems if use it during the game.

**Comment by kaxlabs** [comment]
Uncommenting load world function probably works. I use https://github.com/Folia-Inquisitors/MoreFoWorld for now.

**Comment by kyngs** [comment]
At least as a temporary solution, the world API should only be available from the start. The absence of this is still holding many plugins from moving to Folia.

**Comment by TrueMB** [comment]
Are there any news about un-/loading worlds? I also would need it during runtime.
From what I saw it is planed to add world loading support. Does this also include while running?

**Comment by xunto** [comment]
I was trying to migrate my client's server to Folia, but it seems that because you can't (dynamically) load/unload worlds, I can't do that. It's a server with a gimmick similar to skyblock (e.g. dynamic persistent small maps).

That's a bummer. 😆

If it's still a thing? Or am I doing something wrong?

```
java.lang.UnsupportedOperationException: null
	at org.bukkit.craftbukkit.CraftServer.createWorld(CraftServer.java:1323) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
	at org.bukkit.Bukkit.createWorld(Bukkit.java:838) ~[folia-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.WorldCreator.createWorld(WorldCreator.java:502) ~[folia-api-1.21.4-R0.1-SNAPSHOT.jar:?]
...
	at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179) ~[folia-1.21.4.jar:?]
	at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37) ~[folia-1.21.4.jar:?]
	at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:293) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
	at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:148) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:418) ~[folia-1.21.4.jar:1.21.4-DEV-8af1aef]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:546) ~[concurrentutil-0.0.2.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

```

**Comment by NonSwag** [comment]
World loading is relatively stable even during runtime (you just have to tweak the load code a bit)
World unloading kills the server though 
I haven't had any significant success with it
The best result I had was not crashing the entire server but the world was technically still loaded even though not accessible

**Comment by zombi-dev** [comment]
CanvasMC fixed this already

**Comment by Authoritt** [comment]
I ran into an issue with world loading on the 26.2 branch throws an `UnsupportedOperationException`, and it looks like dynamic world loading/unloading still hasn't been implemented there.
