### ISSUE TITLE
Server crashes when loading chunks.

### ISSUE THREAD

**Issue by ImNotSoftik** [PaperMC/Folia#141]
### Stack trace

https://paste.gg/p/anonymous/00fa2d231fac42bfa4ee0c6901f22810

### Plugin and Datapack List

No

### Actions to reproduce (if known)

I moved the region file from 1.12.2 to 1.20.1 to another location and got this crash, however when I move the 1.20.1 region to another location this does not happen

### Folia version

[17:46:52 INFO]: This server is running Folia version git-Folia-"3cf16ee" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 3cf16ee)

**Comment by ImNotSoftik** [comment]
more 
[io.papermc.paper.threadedregions.TickRegionScheduler] Region #5 centered at chunk [coords, -coords] in world 'world' failed to tick:
net.minecraft.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1695) ~[folia-1.20.1.jar:git-folia-"1189edd"]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:463) ~[folia-1.20.1.jar:git-folia-"1189edd"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1533) ~[folia-1.20.1.jar:git-folia-"1189edd"]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:360) ~[folia-1.20.1.jar:git-folia-"1189edd"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[folia-1.20.1.jar:git-folia-"1189edd"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.1.jar:git-folia-"1189edd"]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.ThreadLocal.get()" because "this.g" is null
	at net.minecraft.world.level.chunk.UpgradeData$BlockFixers$4.processChunk(UpgradeData.java:332) ~[?:?]
	at net.minecraft.world.level.chunk.UpgradeData.upgrade(UpgradeData.java:119) ~[?:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at net.minecraft.world.level.chunk.UpgradeData.upgrade(UpgradeData.java:119) ~[?:?]
	at net.minecraft.world.level.chunk.LevelChunk.postProcessGeneration(LevelChunk.java:1022) ~[?:?]
	at io.papermc.paper.chunk.system.RegionizedPlayerChunkLoader$PlayerChunkLoaderData.updateQueues(RegionizedPlayerChunkLoader.java:878) ~[folia-1.20.1.jar:git-folia-"1189edd"]
	at io.papermc.paper.chunk.system.RegionizedPlayerChunkLoader.tick(RegionizedPlayerChunkLoader.java:244) ~[folia-1.20.1.jar:git-folia-"1189edd"]
	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:448) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:820) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1676) ~[folia-1.20.1.jar:git-folia-"1189edd"]
	... 6 more

**Comment by kugge** [comment]
Does it works on paper ?

**Comment by ocelotpotpie** [comment]
Are you sure you're running build 3cf16ee?

The error in your log is a different git commit of "1189edd".

**Comment by Spottedleaf** [comment]
Fixed by https://github.com/PaperMC/Folia/commit/65667ccd074cec3a600a6d5f117beac04ebac05f
