### ISSUE TITLE
Cannot read field "captureTreeGeneration" because it failed to get world data

### ISSUE THREAD

**Issue by Elikill58** [PaperMC/Folia#150]
### Expected behavior

Be able to get block type.

### Observed/Actual behavior

Error when using `block.getType()` :
```
java.lang.NullPointerException: Cannot read field "captureTreeGeneration" because the return value of "net.minecraft.world.level.World.getCurrentWorldData()" is null
        at net.minecraft.world.level.World.a_(World.java:813)
        at org.bukkit.craftbukkit.v1_20_R1.block.CraftBlock.getType(CraftBlock.java:242)

```

### Steps/models to reproduce

Use `player.getLocation().getBlock().getType()` when receiving player packet, then join on server

### Plugin and Datapack List

- Negativity v2.7-SNAPSHOT (my own - fixing Folia support actually)

### Folia version

This server is running Folia version git-Folia-"f6e91e9" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: f6e91e9)
You are running the latest version

### Other

I think the fact it comes from packet reader can be important to reproduce the error.

**Comment by electronicboy** [comment]
lack of a useful stack trace, but judging from your message, and the error, you're tryna access world state outside of the region context, and thus this will not work

**Comment by Elikill58** [comment]
> lack of a useful stack trace, but judging from your message, and the error, you're tryna access world state outside of the region context, and thus this will not work

Sorry but there is no other interesting line. The full error is this:
```
java.lang.NullPointerException: Cannot read field "captureTreeGeneration" because the return value of "net.minecraft.world.level.World.getCurrentWorldData()" is null
       at net.minecraft.world.level.World.a_(World.java:813)
       at org.bukkit.craftbukkit.v1_20_R1.block.CraftBlock.getType(CraftBlock.java:242)
       at Negativity-2.7-SNAPSHOT.jar//com.elikill58.negativity.spigot.impl.block.SpigotBlock.getType(SpigotBlock.java:23)
       at Negativity-2.7-SNAPSHOT.jar//com.elikill58.negativity.common.PacketListener.onPacketReceive(PacketListener.java:89)
       at Negativity-2.7-SNAPSHOT.jar//com.elikill58.negativity.api.events.EventManager$HandleBasedListener.call(EventManager.java:233)
       at Negativity-2.7-SNAPSHOT.jar//com.elikill58.negativity.api.events.EventManager.lambda$callEvent$1(EventManager.java:175)
       at java.base/java.util.HashMap.forEach(HashMap.java:1421)
       at Negativity-2.7-SNAPSHOT.jar//com.elikill58.negativity.api.events.EventManager.callEvent(EventManager.java:171)
       at Negativity-2.7-SNAPSHOT.jar//com.elikill58.negativity.api.events.EventManager.callEvent(EventManager.java:165)
       at Negativity-2.7-SNAPSHOT.jar//com.elikill58.negativity.api.packets.nms.channels.netty.NettyDecoderHandler.lambda$channelRead$0(NettyDecoderHandler.java:57)
       at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
       at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
       at java.base/java.lang.Thread.run(Thread.java:833)
```
Which doesn't have more information except using more space here.

So, I should use the `GlobalRegionScheduler` to get it? but the given thread will wait or will not be able to get answer?

**Comment by electronicboy** [comment]
No, you need to use the players scheduler in order to touch that stuff, accessing world state off the main thread has NEVER been supported, even moreso on folia

**Comment by GeorgeV220** [comment]
> No, you need to use the players scheduler in order to touch that stuff, accessing world state off the main thread has NEVER been supported, even moreso on folia

Hello, I'm trying to get the block type when I save/load some data, I don't use player.getLocation but this:
Block block = this.toBlock();
Location location = block.getLocation();
String blockType = block.getType().name();

I also need to use a specific scheduler to fix it or something ?

**Comment by Nacioszeczek** [comment]
> 

Please do not use random issues for support and reach out to us on our [Discord](https://discord.gg/papermc) or [forums](https://forums.papermc.io/forums/) instead.
