### ISSUE TITLE
Cannot update owner state asynchronously

### ISSUE THREAD

**Issue by xyfwdy** [PaperMC/Folia#152]
### Expected behavior

```
[08:51:09] [Region Scheduler Thread #1/ERROR]: Thread Region Scheduler Thread #1 failed main thread check: Cannot update owner state asynchronously
java.lang.Throwable: null
	at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:78) ~[folia-1.20.1.jar:git-Folia-"372d479"]
	at net.minecraft.world.entity.projectile.Projectile.getOwnerRaw(Projectile.java:78) ~[?:?]
	at net.minecraft.world.entity.projectile.Projectile.getOwner(Projectile.java:71) ~[?:?]
	at net.minecraft.world.entity.projectile.FishingHook.getPlayerOwner(FishingHook.java:627) ~[?:?]
	at net.minecraft.world.entity.projectile.FishingHook.retrieve(FishingHook.java:479) ~[?:?]
	at net.minecraft.world.item.FishingRodItem.use(FishingRodItem.java:32) ~[?:?]
	at net.minecraft.world.item.ItemStack.use(ItemStack.java:546) ~[folia-1.20.1.jar:git-Folia-"372d479"]
	at net.minecraft.server.level.ServerPlayerGameMode.useItem(ServerPlayerGameMode.java:481) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItem(ServerGamePacketListenerImpl.java:2131) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:32) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:8) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:52) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:75) ~[?:?]
	at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:173) ~[folia-1.20.1.jar:git-Folia-"372d479"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1523) ~[folia-1.20.1.jar:git-Folia-"372d479"]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:360) ~[folia-1.20.1.jar:git-Folia-"372d479"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[folia-1.20.1.jar:git-Folia-"372d479"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.1.jar:git-Folia-"372d479"]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
[08:51:09] [Region Scheduler Thread #1/ERROR]: Failed to handle packet net.minecraft.network.protocol.game.PacketPlayInBlockPlace@33d0d944, suppressing error
java.lang.IllegalStateException: Cannot update owner state asynchronously
	at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:79) ~[folia-1.20.1.jar:git-Folia-"372d479"]
	at net.minecraft.world.entity.projectile.Projectile.getOwnerRaw(Projectile.java:78) ~[?:?]
	at net.minecraft.world.entity.projectile.Projectile.getOwner(Projectile.java:71) ~[?:?]
	at net.minecraft.world.entity.projectile.FishingHook.getPlayerOwner(FishingHook.java:627) ~[?:?]
	at net.minecraft.world.entity.projectile.FishingHook.retrieve(FishingHook.java:479) ~[?:?]
	at net.minecraft.world.item.FishingRodItem.use(FishingRodItem.java:32) ~[?:?]
	at net.minecraft.world.item.ItemStack.use(ItemStack.java:546) ~[folia-1.20.1.jar:git-Folia-"372d479"]
	at net.minecraft.server.level.ServerPlayerGameMode.useItem(ServerPlayerGameMode.java:481) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItem(ServerGamePacketListenerImpl.java:2131) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:32) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:8) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:52) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:75) ~[?:?]
	at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:173) ~[folia-1.20.1.jar:git-Folia-"372d479"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1523) ~[folia-1.20.1.jar:git-Folia-"372d479"]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:360) ~[folia-1.20.1.jar:git-Folia-"372d479"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[folia-1.20.1.jar:git-Folia-"372d479"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.1.jar:git-Folia-"372d479"]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
Failed to handle packet net.minecraft.network.protocol.game.PacketPlayInBlockPlace@33d0d944, suppressing error
java.lang.IllegalStateException: Cannot update owner state asynchronously
	at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:79) ~[folia-1.20.1.jar:git-Folia-"372d479"]
	at net.minecraft.world.entity.projectile.Projectile.getOwnerRaw(Projectile.java:78) ~[?:?]
	at net.minecraft.world.entity.projectile.Projectile.getOwner(Projectile.java:71) ~[?:?]
	at net.minecraft.world.entity.projectile.FishingHook.getPlayerOwner(FishingHook.java:627) ~[?:?]
	at net.minecraft.world.entity.projectile.FishingHook.retrieve(FishingHook.java:479) ~[?:?]
	at net.minecraft.world.item.FishingRodItem.use(FishingRodItem.java:32) ~[?:?]
	at net.minecraft.world.item.ItemStack.use(ItemStack.java:546) ~[folia-1.20.1.jar:git-Folia-"372d479"]
	at net.minecraft.server.level.ServerPlayerGameMode.useItem(ServerPlayerGameMode.java:481) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItem(ServerGamePacketListenerImpl.java:2131) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:32) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:8) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:52) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:75) ~[?:?]
	at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:173) ~[folia-1.20.1.jar:git-Folia-"372d479"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1523) ~[folia-1.20.1.jar:git-Folia-"372d479"]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:360) ~[folia-1.20.1.jar:git-Folia-"372d479"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[folia-1.20.1.jar:git-Folia-"372d479"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.1.jar:git-Folia-"372d479"]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
Failed to handle packet net.minecraft.network.protocol.game.PacketPlayInBlockPlace@2a7f5657, suppressing error
java.lang.IllegalStateException: Cannot update owner state asynchronously
	at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:79) ~[folia-1.20.1.jar:git-Folia-"372d479"]
	at net.minecraft.world.entity.projectile.Projectile.getOwnerRaw(Projectile.java:78) ~[?:?]
	at net.minecraft.world.entity.projectile.Projectile.getOwner(Projectile.java:71) ~[?:?]
	at net.minecraft.world.entity.projectile.FishingHook.getPlayerOwner(FishingHook.java:627) ~[?:?]
	at net.minecraft.world.entity.projectile.FishingHook.retrieve(FishingHook.java:479) ~[?:?]
	at net.minecraft.world.item.FishingRodItem.use(FishingRodItem.java:32) ~[?:?]
	at net.minecraft.world.item.ItemStack.use(ItemStack.java:546) ~[folia-1.20.1.jar:git-Folia-"372d479"]
	at net.minecraft.server.level.ServerPlayerGameMode.useItem(ServerPlayerGameMode.java:481) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItem(ServerGamePacketListenerImpl.java:2131) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:32) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:8) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:52) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:75) ~[?:?]
	at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:173) ~[folia-1.20.1.jar:git-Folia-"372d479"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1523) ~[folia-1.20.1.jar:git-Folia-"372d479"]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:360) ~[folia-1.20.1.jar:git-Folia-"372d479"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[folia-1.20.1.jar:git-Folia-"372d479"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.1.jar:git-Folia-"372d479"]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
```

### Observed/Actual behavior

found at check log 

### Steps/models to reproduce

unknown

### Plugin and Datapack List

original plugins

### Folia version

This server is running Folia version git-Folia-"372d479" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 372d479)
You are running the latest version
Previous version: git-Folia-"f6e91e9" (MC: 1.20.1)

**Comment by SplotyCode** [comment]
I believe this is known and delayed https://github.com/PaperMC/Folia/blob/master/regiontodo.txt#L27

**Comment by PedroMPagani** [comment]
This is probably fixed on the latest versions already. Because I have not seen this on 1.21.1 already.
