### ISSUE TITLE
Plugins listed on Hangar don't work

### ISSUE THREAD

**Issue by KuebelHund** [PaperMC/Folia#155]
### Expected behavior

Server starting and loading all plugins with any issues

### Observed/Actual behavior

errors loading most of the plugins:

container@pterodactyl~ java -version
openjdk version "17.0.8.1" 2023-08-24
OpenJDK Runtime Environment Temurin-17.0.8.1+1 (build 17.0.8.1+1)
OpenJDK 64-Bit Server VM Temurin-17.0.8.1+1 (build 17.0.8.1+1, mixed mode, sharing)
container@pterodactyl~ java --add-modules=jdk.incubator.vector -Xms128M -Xmx61440M -Dterminal.jline=false -Dterminal.ansi=true -jar server.jar
WARNING: Using incubator modules: jdk.incubator.vector
Starting org.bukkit.craftbukkit.Main
System Info: Java 17 (OpenJDK 64-Bit Server VM 17.0.8.1+1) Host: Linux 5.15.0-76-generic (amd64)
Loading libraries, please wait...
[08:50:40 ERROR]: [DirectoryProviderSource] Error loading plugin: Directory 'plugins/PluginPortal-1.5.0.jar' failed to load!
java.lang.RuntimeException: Directory 'plugins/PluginPortal-1.5.0.jar' failed to load!
        at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:59) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.lambda$registerProviders$1(DirectoryProviderSource.java:34) ~[folia-1.20.1.jar:git-Folia-17]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:32) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:14) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:14) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:100) ~[folia-1.20.1.jar:git-Folia-17]
        at net.minecraft.server.Main.main(Main.java:126) ~[folia-1.20.1.jar:git-Folia-17]
        at org.bukkit.craftbukkit.Main.main(Main.java:316) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.RuntimeException: Could not load plugin 'PluginPortal v1.5.0' as it is not marked as supporting Folia!
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProviderFactory.build(SpigotPluginProviderFactory.java:22) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProviderFactory.build(SpigotPluginProviderFactory.java:16) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paper.plugin.provider.type.PluginFileType.register(PluginFileType.java:71) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:57) ~[folia-1.20.1.jar:git-Folia-17]
        ... 20 more
[08:50:40 ERROR]: [DirectoryProviderSource] Error loading plugin: Directory 'plugins/Parties-3.2.12.jar' failed to load!
java.lang.RuntimeException: Directory 'plugins/Parties-3.2.12.jar' failed to load!
        at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:59) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.lambda$registerProviders$1(DirectoryProviderSource.java:34) ~[folia-1.20.1.jar:git-Folia-17]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:32) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:14) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:14) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:100) ~[folia-1.20.1.jar:git-Folia-17]
        at net.minecraft.server.Main.main(Main.java:126) ~[folia-1.20.1.jar:git-Folia-17]
        at org.bukkit.craftbukkit.Main.main(Main.java:316) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.RuntimeException: Could not load plugin 'Parties v3.2.12' as it is not marked as supporting Folia!
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProviderFactory.build(SpigotPluginProviderFactory.java:22) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProviderFactory.build(SpigotPluginProviderFactory.java:16) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paper.plugin.provider.type.PluginFileType.register(PluginFileType.java:71) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:57) ~[folia-1.20.1.jar:git-Folia-17]
        ... 20 more
[08:50:40 ERROR]: [DirectoryProviderSource] Error loading plugin: Directory 'plugins/BlueMap-3.16-spigot.jar' failed to load!
java.lang.RuntimeException: Directory 'plugins/BlueMap-3.16-spigot.jar' failed to load!
        at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:59) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.lambda$registerProviders$1(DirectoryProviderSource.java:34) ~[folia-1.20.1.jar:git-Folia-17]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:32) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:14) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:14) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:100) ~[folia-1.20.1.jar:git-Folia-17]
        at net.minecraft.server.Main.main(Main.java:126) ~[folia-1.20.1.jar:git-Folia-17]
        at org.bukkit.craftbukkit.Main.main(Main.java:316) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.RuntimeException: Could not load plugin 'BlueMap v3.16' as it is not marked as supporting Folia!
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProviderFactory.build(SpigotPluginProviderFactory.java:22) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProviderFactory.build(SpigotPluginProviderFactory.java:16) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paper.plugin.provider.type.PluginFileType.register(PluginFileType.java:71) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:57) ~[folia-1.20.1.jar:git-Folia-17]
        ... 20 more
[08:50:40 ERROR]: [DirectoryProviderSource] Error loading plugin: Directory 'plugins/TreeFella-1.3.jar' failed to load!
java.lang.RuntimeException: Directory 'plugins/TreeFella-1.3.jar' failed to load!
        at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:59) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.lambda$registerProviders$1(DirectoryProviderSource.java:34) ~[folia-1.20.1.jar:git-Folia-17]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:32) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:14) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:14) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:100) ~[folia-1.20.1.jar:git-Folia-17]
        at net.minecraft.server.Main.main(Main.java:126) ~[folia-1.20.1.jar:git-Folia-17]
        at org.bukkit.craftbukkit.Main.main(Main.java:316) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.RuntimeException: Could not load plugin 'TreeFella v1.2' as it is not marked as supporting Folia!
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProviderFactory.build(SpigotPluginProviderFactory.java:22) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProviderFactory.build(SpigotPluginProviderFactory.java:16) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paper.plugin.provider.type.PluginFileType.register(PluginFileType.java:71) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:57) ~[folia-1.20.1.jar:git-Folia-17]
        ... 20 more
[08:50:40 ERROR]: [DirectoryProviderSource] Error loading plugin: Directory 'plugins/tabtps-spigot-1.3.18.jar' failed to load!
java.lang.RuntimeException: Directory 'plugins/tabtps-spigot-1.3.18.jar' failed to load!
        at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:59) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.lambda$registerProviders$1(DirectoryProviderSource.java:34) ~[folia-1.20.1.jar:git-Folia-17]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:32) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:14) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:14) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:100) ~[folia-1.20.1.jar:git-Folia-17]
        at net.minecraft.server.Main.main(Main.java:126) ~[folia-1.20.1.jar:git-Folia-17]
        at org.bukkit.craftbukkit.Main.main(Main.java:316) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.RuntimeException: Could not load plugin 'TabTPS v1.3.18' as it is not marked as supporting Folia!
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProviderFactory.build(SpigotPluginProviderFactory.java:22) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProviderFactory.build(SpigotPluginProviderFactory.java:16) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paper.plugin.provider.type.PluginFileType.register(PluginFileType.java:71) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:57) ~[folia-1.20.1.jar:git-Folia-17]
        ... 20 more
[08:50:40 ERROR]: [DirectoryProviderSource] Error loading plugin: Directory 'plugins/ClientCatcher-3.1.1.jar' failed to load!
java.lang.RuntimeException: Directory 'plugins/ClientCatcher-3.1.1.jar' failed to load!
        at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:59) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.lambda$registerProviders$1(DirectoryProviderSource.java:34) ~[folia-1.20.1.jar:git-Folia-17]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:32) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:14) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:14) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:100) ~[folia-1.20.1.jar:git-Folia-17]
        at net.minecraft.server.Main.main(Main.java:126) ~[folia-1.20.1.jar:git-Folia-17]
        at org.bukkit.craftbukkit.Main.main(Main.java:316) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Directory 'plugins/ClientCatcher-3.1.1.jar' does not contain a paper-plugin.yml or plugin.yml! Could not determine plugin type, cannot load a plugin from it!
        at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:54) ~[folia-1.20.1.jar:git-Folia-17]
        ... 20 more
[08:50:40 ERROR]: [DirectoryProviderSource] Error loading plugin: Directory 'plugins/BetterMessages-3.2.1.jar' failed to load!
java.lang.RuntimeException: Directory 'plugins/BetterMessages-3.2.1.jar' failed to load!
        at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:59) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.lambda$registerProviders$1(DirectoryProviderSource.java:34) ~[folia-1.20.1.jar:git-Folia-17]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:32) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:14) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:14) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:100) ~[folia-1.20.1.jar:git-Folia-17]
        at net.minecraft.server.Main.main(Main.java:126) ~[folia-1.20.1.jar:git-Folia-17]
        at org.bukkit.craftbukkit.Main.main(Main.java:316) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.RuntimeException: Could not load plugin 'BetterMessages v3.2.1' as it is not marked as supporting Folia!
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProviderFactory.build(SpigotPluginProviderFactory.java:22) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProviderFactory.build(SpigotPluginProviderFactory.java:16) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paper.plugin.provider.type.PluginFileType.register(PluginFileType.java:71) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:57) ~[folia-1.20.1.jar:git-Folia-17]
        ... 20 more
[08:50:40 ERROR]: [DirectoryProviderSource] Error loading plugin: Directory 'plugins/Plan-5.5-build-2461.jar' failed to load!
java.lang.RuntimeException: Directory 'plugins/Plan-5.5-build-2461.jar' failed to load!
        at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:59) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.lambda$registerProviders$1(DirectoryProviderSource.java:34) ~[folia-1.20.1.jar:git-Folia-17]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:32) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:14) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:14) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:100) ~[folia-1.20.1.jar:git-Folia-17]
        at net.minecraft.server.Main.main(Main.java:126) ~[folia-1.20.1.jar:git-Folia-17]
        at org.bukkit.craftbukkit.Main.main(Main.java:316) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.RuntimeException: Could not load plugin 'Plan v5.5 build 2461' as it is not marked as supporting Folia!
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProviderFactory.build(SpigotPluginProviderFactory.java:22) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProviderFactory.build(SpigotPluginProviderFactory.java:16) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paper.plugin.provider.type.PluginFileType.register(PluginFileType.java:71) ~[folia-1.20.1.jar:git-Folia-17]
        at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:57) ~[folia-1.20.1.jar:git-Folia-17]
        ... 20 more

### Steps/models to reproduce

install a server on linux using pterodactyl and its folia egg, drag plugins into plugin folder, start.

### Plugin and Datapack List

plugins list
[08:56:12 INFO]: Server Plugins (7):
[08:56:12 INFO]: Bukkit Plugins:
[08:56:12 INFO]:  - Chunky, CoreProtect, FarmControl, FreedomChat, GSit, Maintenance, voicechat

datapacks: NONE

### Folia version

version
[08:56:59 INFO]: Checking version, please wait...
[08:56:59 INFO]: This server is running Folia version git-Folia-17 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: edafbce)
You are running the latest version
Previous version: git-Purpur-2060 (MC: 1.20.1)

**Comment by Nacioszeczek** [comment]
Please report the plugins using the Report button on the website or contact their authors. 
This is irrelevant for the issue tracker.
