### ISSUE TITLE
block.setData() and block.getData and etc. bug

### ISSUE THREAD

**Issue by Alienn-Know** [PaperMC/Folia#158]
### Stack trace

[10:54:06 ERROR]: Thread Region Scheduler Thread #0 failed main thread check: Cannot read world asynchronously
java.lang.Throwable: null
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:57) ~[folia-1.19.4.jar:git-Folia-"ca3b7ad"]        at org.bukkit.craftbukkit.v1_19_R3.block.CraftBlock.getNMS(CraftBlock.java:86) ~[folia-1.19.4.jar:git-Folia-"ca3b7ad"]
        at org.bukkit.craftbukkit.v1_19_R3.block.CraftBlock.setTypeAndData(CraftBlock.java:207) ~[folia-1.19.4.jar:git-Folia-"ca3b7ad"]
        at org.bukkit.craftbukkit.v1_19_R3.block.CraftBlock.setBlockData(CraftBlock.java:203) ~[folia-1.19.4.jar:git-Folia-"ca3b7ad"]
        at org.bukkit.craftbukkit.v1_19_R3.block.CraftBlock.setBlockData(CraftBlock.java:197) ~[folia-1.19.4.jar:git-Folia-"ca3b7ad"]
        at org.example.heroesmy.untitled.skill.skills.active.Light.restoreReplacedBlocks(Light.java:142) ~[untitled-1.0-SNAPSHOT.jar:?]
        at org.example.heroesmy.untitled.skill.skills.active.Light.lambda$useSkill$2(Light.java:125) ~[untitled-1.0-SNAPSHOT.jar:?]
        at org.example.heroesmy.untitled.sheduler.impl.FoliaTaskScheduler.lambda$run$1(FoliaTaskScheduler.java:54) ~[untitled-1.0-SNAPSHOT.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaEntityScheduler$EntityScheduledTask.accept(FoliaEntityScheduler.java:167) ~[folia-1.19.4.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaEntityScheduler$EntityScheduledTask.accept(FoliaEntityScheduler.java:114) ~[folia-1.19.4.jar:?]
        at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:173) ~[folia-1.19.4.jar:git-Folia-"ca3b7ad"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1527) ~[folia-1.19.4.jar:git-Folia-"ca3b7ad"]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:360) ~[folia-1.19.4.jar:git-Folia-"ca3b7ad"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[folia-1.19.4.jar:git-Folia-"ca3b7ad"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.19.4.jar:git-Folia-"ca3b7ad"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[10:54:06 WARN]: [untitled] Entity task for untitled v1.0-SNAPSHOT generated an exception
java.lang.IllegalStateException: Cannot read world asynchronously
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:58) ~[folia-1.19.4.jar:git-Folia-"ca3b7ad"]        at org.bukkit.craftbukkit.v1_19_R3.block.CraftBlock.getNMS(CraftBlock.java:86) ~[folia-1.19.4.jar:git-Folia-"ca3b7ad"]
        at org.bukkit.craftbukkit.v1_19_R3.block.CraftBlock.setTypeAndData(CraftBlock.java:207) ~[folia-1.19.4.jar:git-Folia-"ca3b7ad"]
        at org.bukkit.craftbukkit.v1_19_R3.block.CraftBlock.setBlockData(CraftBlock.java:203) ~[folia-1.19.4.jar:git-Folia-"ca3b7ad"]
        at org.bukkit.craftbukkit.v1_19_R3.block.CraftBlock.setBlockData(CraftBlock.java:197) ~[folia-1.19.4.jar:git-Folia-"ca3b7ad"]
        at org.example.heroesmy.untitled.skill.skills.active.Light.restoreReplacedBlocks(Light.java:142) ~[untitled-1.0-SNAPSHOT.jar:?]
        at org.example.heroesmy.untitled.skill.skills.active.Light.lambda$useSkill$2(Light.java:125) ~[untitled-1.0-SNAPSHOT.jar:?]
        at org.example.heroesmy.untitled.sheduler.impl.FoliaTaskScheduler.lambda$run$1(FoliaTaskScheduler.java:54) ~[untitled-1.0-SNAPSHOT.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaEntityScheduler$EntityScheduledTask.accept(FoliaEntityScheduler.java:167) ~[folia-1.19.4.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaEntityScheduler$EntityScheduledTask.accept(FoliaEntityScheduler.java:114) ~[folia-1.19.4.jar:?]
        at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:173) ~[folia-1.19.4.jar:git-Folia-"ca3b7ad"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1527) ~[folia-1.19.4.jar:git-Folia-"ca3b7ad"]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:360) ~[folia-1.19.4.jar:git-Folia-"ca3b7ad"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[folia-1.19.4.jar:git-Folia-"ca3b7ad"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.19.4.jar:git-Folia-"ca3b7ad"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Plugin and Datapack List

[11:37:45 INFO]: Bukkit Plugins:
[11:37:45 INFO]:  - ChestShop, Chunky, HealthBarFolia, LootChest, spark, SternalBoard, TeleportFolia, Towny, TownyChat, untitled
[11:37:45 INFO]:  Vault, ViaBackwards, ViaRewind, ViaVersion

### Actions to reproduce (if known)

My plugin is supposed to replace certain blocks stored in the HashMap every 5 ticks, the blocks are replaced normally, but as soon as I teleport to another location I get this error. As I understand it, the Thread that can manipulate blocks in that area is missing, but how to solve this problem??

### Folia version

1.19.4

**Comment by electronicboy** [comment]
1) 1.19.4 is no longer supported
2) You teleported away, your entity is no longer in that region, and thus are no longer ticked in that region and thus no longer own it. If you wanna do mutations to the world, you need to use the region scheduler to safely do it

**Comment by Alienn-Know** [comment]
how to do it?

**Comment by Alienn-Know** [comment]
> 1. 1.19.4 is no longer supported
> 2. You teleported away, your entity is no longer in that region, and thus are no longer ticked in that region and thus no longer own it. If you wanna do mutations to the world, you need to use the region scheduler to safely do it

How to doing this? I use regionSheduler

I use RegionSheduler, but when I teleport, the old region (owning the blocks) is deleted and a new one is created in the place where I teleported, and I get this error

**Comment by Alienn-Know** [comment]
EntitySheduler attached to the player also does not help (the old region is deleted and an error occurs), GlobalRegionSheduler and AsyncSheduler also do not have access to blocks

**Comment by masmc05** [comment]
> > 1. 1.19.4 is no longer supported
> > 2. You teleported away, your entity is no longer in that region, and thus are no longer ticked in that region and thus no longer own it. If you wanna do mutations to the world, you need to use the region scheduler to safely do it
> 
> How to doing this? I use regionSheduler
> 
> I use RegionSheduler, but when I teleport, the old region (owning the blocks) is deleted and a new one is created in the place where I teleported, and I get this error

show the code, you most likely made an error, as region scheduler should create a temporary region if it's missing
