### ISSUE TITLE
Server crash on player disconnect

### ISSUE THREAD

**Issue by roggy666** [PaperMC/Folia#162]
### Stack trace

[00:13:17] [Region Scheduler Thread #2/ERROR]: Thread Region Scheduler Thread #2 failed main thread check: Cannot remove entity off-main
java.lang.Throwable: null
	at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:78) ~[folia-1.20.1.jar:git-Folia-"372d479"]
	at net.minecraft.world.entity.Entity.setRemoved(Entity.java:5455) ~[folia-1.20.1.jar:git-Folia-"372d479"]
	at net.minecraft.world.entity.Entity.remove(Entity.java:697) ~[folia-1.20.1.jar:git-Folia-"372d479"]
	at net.minecraft.world.entity.LivingEntity.remove(LivingEntity.java:769) ~[?:?]
	at net.minecraft.world.entity.player.Player.remove(Player.java:1497) ~[?:?]
	at net.minecraft.server.level.ServerLevel.removePlayerImmediately(ServerLevel.java:1783) ~[?:?]
	at net.minecraft.server.players.PlayerList.remove(PlayerList.java:738) ~[folia-1.20.1.jar:git-Folia-"372d479"]
	at net.minecraft.server.players.PlayerList.remove(PlayerList.java:677) ~[folia-1.20.1.jar:git-Folia-"372d479"]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2213) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2192) ~[?:?]
	at net.minecraft.network.Connection.handleDisconnection(Connection.java:858) ~[?:?]
	at io.papermc.paper.threadedregions.RegionizedWorldData.tickConnections(RegionizedWorldData.java:462) ~[folia-1.20.1.jar:git-Folia-"372d479"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1527) ~[folia-1.20.1.jar:git-Folia-"372d479"]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:360) ~[folia-1.20.1.jar:git-Folia-"372d479"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[folia-1.20.1.jar:git-Folia-"372d479"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.1.jar:git-Folia-"372d479"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[00:13:17] [Region Scheduler Thread #2/ERROR]: [io.papermc.paper.threadedregions.TickRegionScheduler] Region #1 centered at chunk [0, 7] in world 'world' failed to tick:
java.lang.IllegalStateException: Cannot remove entity off-main
	at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:79) ~[folia-1.20.1.jar:git-Folia-"372d479"]
	at net.minecraft.world.entity.Entity.setRemoved(Entity.java:5455) ~[folia-1.20.1.jar:git-Folia-"372d479"]
	at net.minecraft.world.entity.Entity.remove(Entity.java:697) ~[folia-1.20.1.jar:git-Folia-"372d479"]
	at net.minecraft.world.entity.LivingEntity.remove(LivingEntity.java:769) ~[?:?]
	at net.minecraft.world.entity.player.Player.remove(Player.java:1497) ~[?:?]
	at net.minecraft.server.level.ServerLevel.removePlayerImmediately(ServerLevel.java:1783) ~[?:?]
	at net.minecraft.server.players.PlayerList.remove(PlayerList.java:738) ~[folia-1.20.1.jar:git-Folia-"372d479"]
	at net.minecraft.server.players.PlayerList.remove(PlayerList.java:677) ~[folia-1.20.1.jar:git-Folia-"372d479"]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2213) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2192) ~[?:?]
	at net.minecraft.network.Connection.handleDisconnection(Connection.java:858) ~[?:?]
	at io.papermc.paper.threadedregions.RegionizedWorldData.tickConnections(RegionizedWorldData.java:462) ~[folia-1.20.1.jar:git-Folia-"372d479"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1527) ~[folia-1.20.1.jar:git-Folia-"372d479"]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:360) ~[folia-1.20.1.jar:git-Folia-"372d479"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[folia-1.20.1.jar:git-Folia-"372d479"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.1.jar:git-Folia-"372d479"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[00:13:17] [Region shutdown thread/INFO]: [RegionShutdownThread] Awaiting scheduler termination for 60s
[00:13:17] [Region shutdown thread/INFO]: [RegionShutdownThread] Scheduler halted
[00:13:17] [Region shutdown thread/INFO]: Stopping server

### Plugin and Datapack List

WorldGuard, WorldEdit, zAuctionHouseV3, Vault, EssentialsX, FancyNPCs

### Folia version

Previous version: git-Folia-"f6e91e9" (MC: 1.20.1)

### Other

One of my player disconnected and server was crashed, I can't know all the details. But this bug is serious

**Comment by Q2297045667** [comment]
Please use the latest version

**Comment by roggy666** [comment]
> Please use the dev/1.20.2 latest version

Oh, it problematic for me, I will need to update a lot of other plugins, maybe is it possible to fix on 1.20.1? I just don’t see the point in switching to 1.20.2 now, because there is already 1.20.3 in snapshots

**Comment by Q2297045667** [comment]
> > Please use the dev/1.20.2 latest version
> 
> Oh, it problematic for me, I will need to update a lot of other plugins, maybe is it possible to fix on 1.20.1? I just don’t see the point in switching to 1.20.2 now, because there is already 1.20.3 in snapshots

Yes, I remember Folia 1.20.2 fixed this issue, but I'm not very sure
