### ISSUE TITLE
Cannot use Server#createCommandSender with Server#dispatchCommand on Folia

### ISSUE THREAD

**Issue by Vankka** [PaperMC/Folia#163]
### Expected behavior

Able to run `Server#dispatchCommand` with a `CommandSender` provided by `Server#createCommandSender(Consumer)` and have it succeed

### Observed/Actual behavior

Unable to do so,
```java
[14:50:15 WARN]: [example-plugin] Global task for example-plugin v1.0 generated an exception
java.lang.UnsupportedOperationException: Dispatching command for io.papermc.paper.commands.FeedbackForwardingSender@1d47f198
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1022) ~[folia-1.20.1.jar:git-Folia-"edafbce"]
	at dev.vankka.exampleplugin.ExamplePlugin.lambda$onCommand$1(ExamplePlugin.java:16) ~[example-plugin-1.0-SNAPSHOT.jar:?]
	at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.lambda$execute$0(FoliaGlobalRegionScheduler.java:47) ~[folia-1.20.1.jar:?]
	at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179) ~[folia-1.20.1.jar:?]
	at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37) ~[folia-1.20.1.jar:?]
	at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:294) ~[folia-1.20.1.jar:git-Folia-"edafbce"]
	at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:149) ~[folia-1.20.1.jar:git-Folia-"edafbce"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[folia-1.20.1.jar:git-Folia-"edafbce"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.1.jar:git-Folia-"edafbce"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Steps/models to reproduce

```java
public final class ExamplePlugin extends JavaPlugin {

    @Override
    public boolean onCommand(@NotNull CommandSender __, @NotNull Command ___, @NotNull String ____, @NotNull String[] _____) {
        Server server = getServer();
        server.getGlobalRegionScheduler().execute(this, () -> {
            CommandSender forwardingSender = server.createCommandSender(component -> {});
            server.dispatchCommand(forwardingSender, "list");
        });

        return true;
    }
}

```

### Plugin and Datapack List

Only the above test plugin

### Folia version

```
> ver
[14:51:29 INFO]: Checking version, please wait...
[14:51:29 INFO]: This server is running Folia version git-Folia-"edafbce" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: edafbce)
You are running the latest version
```

### Other

https://github.com/PaperMC/Folia/blob/edafbcef6884cffe493e62cd71f4957708fba7ff/patches/server/0003-Threaded-Regions.patch#L22413-L22414 - IllegalStateException thrown here

`Server#createCommandSender` returns a
-  `io.papermc.paper.commands.FeedbackForwardingSender`
   - `org.bukkit.craftbukkit.command.ServerCommandSender`
      - `org.bukkit.command.CommandSender`

**Comment by jpenilla** [comment]
Fixed in 1.20.2
