### ISSUE TITLE
Thread Region Scheduler Thread #0 failed main thread check: Scheduling chunk load off-main

### ISSUE THREAD

**Issue by ColdeZhang** [PaperMC/Folia#206]
### Expected behavior

`Collection<Chunk> chunks = world.getForceLoadedChunks();`

It should get all force loaded chunks of this world.

### Observed/Actual behavior

It seems worked on main world, but failed when it comes to world_nether, and throw null dump below.

```
[17:26:50 ERROR]: Thread Region Scheduler Thread #0 failed main thread check: Scheduling chunk load off-main
java.lang.Throwable: null
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:71) ~[deerfolia-1.20.4.jar:git-Folia-"46d8526"]
        at net.minecraft.server.level.ServerChunkCache.getChunkFutureMainThread(ServerChunkCache.java:293) ~[deerfolia-1.20.4.jar:git-Folia-"46d8526"]
        at net.minecraft.server.level.ServerChunkCache.getChunk(ServerChunkCache.java:223) ~[deerfolia-1.20.4.jar:git-Folia-"46d8526"]
        at net.minecraft.world.level.chunk.ChunkSource.getChunk(ChunkSource.java:12) ~[deerfolia-1.20.4.jar:git-Folia-"46d8526"]
        at org.bukkit.craftbukkit.v1_20_R3.CraftWorld.getChunkAt(CraftWorld.java:350) ~[deerfolia-1.20.4.jar:git-Folia-"46d8526"]
        at org.bukkit.craftbukkit.v1_20_R3.CraftWorld.getForceLoadedChunks(CraftWorld.java:698) ~[deerfolia-1.20.4.jar:git-Folia-"46d8526"]
```

### Steps/models to reproduce

Run code below in plugin onEnable()

```
this.getServer().getGlobalRegionScheduler().run(this, (instance) -> {
            for (World world : this.getServer().getWorlds()) {
                Collection<Chunk> chunks = world.getForceLoadedChunks();
                for (Chunk chunk : chunks) {
                    world.setChunkForceLoaded(chunk.getX(), chunk.getZ(), false);
                }
            }
        });
```

### Plugin and Datapack List

no

### Folia version

git-Folia-"46d8526" (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 46d8526)

**Comment by ColdeZhang** [comment]
Sorry for report this issue in the wrong repo
