### ISSUE TITLE
getworld().spawn() or getworld().spawnentity() doesnt work in folia schedulers.

### ISSUE THREAD

**Issue by kgncengiz** [PaperMC/Folia#208]
### Expected behavior

entity spawns normally.

### Observed/Actual behavior

[15:46:08 WARN]: [MCCcore] Global task for MCCcore v1.0-SNAPSHOT generated an exception
java.lang.NullPointerException: Cannot read field "captureDrops" because the return value of "net.minecraft.server.level.WorldServer.getCurrentWorldData()" is null
        at net.minecraft.server.level.ServerLevel.addEntity(ServerLevel.java:1879) ~[?:?]
        at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1807) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftWorld.addEntityToWorld(CraftWorld.java:1093) ~[folia-1.20.4.jar:git-Folia-24]
        at org.bukkit.craftbukkit.v1_20_R3.CraftRegionAccessor.addEntity(CraftRegionAccessor.java:457) ~[folia-1.20.4.jar:git-Folia-24]
        at org.bukkit.craftbukkit.v1_20_R3.CraftRegionAccessor.spawn(CraftRegionAccessor.java:420) ~[folia-1.20.4.jar:git-Folia-24]
        at org.bukkit.craftbukkit.v1_20_R3.CraftRegionAccessor.spawn(CraftRegionAccessor.java:414) ~[folia-1.20.4.jar:git-Folia-24]
        at org.bukkit.craftbukkit.v1_20_R3.CraftRegionAccessor.spawn(CraftRegionAccessor.java:400) ~[folia-1.20.4.jar:git-Folia-24]
        at org.bukkit.craftbukkit.v1_20_R3.CraftRegionAccessor.spawnEntity(CraftRegionAccessor.java:296) ~[folia-1.20.4.jar:git-Folia-24]
        at net.apvp.mcccore.MCCcore.lambda$onPlayerCommand$2(MCCcore.java:93) ~[MCCcore-1.0-SNAPSHOT.jar:?]
        at net.apvp.mcccore.Scheduler.lambda$runTimer$1(Scheduler.java:33) ~[MCCcore-1.0-SNAPSHOT.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179) ~[folia-1.20.4.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37) ~[folia-1.20.4.jar:?]
        at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:293) ~[folia-1.20.4.jar:git-Folia-24]
        at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:148) ~[folia-1.20.4.jar:git-Folia-24]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[folia-1.20.4.jar:git-Folia-24]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.4.jar:git-Folia-24]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

### Steps/models to reproduce

just try to use Bukkit.getWorld("world").spawn(location, cow.class); or Bukkit.getWorld("world").spawnEntity(location, EntityType.COW); in a folia scheduler. I encountered this bug while i was trying to spawn an entity with the following class and code ```
public static Task runTimer(Runnable runnable, long delayTicks, long periodTicks) {
        if (isFolia)
            return new Task(Bukkit.getGlobalRegionScheduler()
                    .runAtFixedRate(MCCcore.getInstance(), t -> runnable.run(), delayTicks < 1 ? 1 : delayTicks, periodTicks));

        else
            return new Task(Bukkit.getScheduler().runTaskTimer(MCCcore.getInstance(), runnable, delayTicks, periodTicks));
    }

villagerspawn = Scheduler.runTimer(() -> {
                Villager villager = (Villager) bossloc3.getWorld().spawnEntity(location, EntityType.VILLAGER);

                }, 0, 20);
``` i hope that's enough for you to reproduce the same bug.

### Plugin and Datapack List

none, i am developing my own plugin.

### Folia version

[15:52:13 INFO]: This server is running Folia version git-Folia-24 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: e97b1ee)
You are 2 version(s) behind
Download the new version at: https://papermc.io/downloads/paper

### Other

have a good day.

**Comment by HSGamer** [comment]
You can't spawn entities at `GlobalRegionScheduler`. It needs to be in a `RegionScheduler`.
https://jd.papermc.io/folia/1.20/org/bukkit/Bukkit.html#getRegionScheduler()

**Comment by kgncengiz** [comment]
sorry for the bad code GitHub messed up the code bud anyway thanks.
