### ISSUE TITLE
Server crash from an entity

### ISSUE THREAD

**Issue by Press22300** [PaperMC/Folia#211]
### Stack trace

```
[19:20:52] [Region Scheduler Thread #21/ERROR]: Entity threw exception at oneblock:53585.58354723191,203.0,24006.97783524526
java.lang.ArrayIndexOutOfBoundsException: null

[19:20:52] [Region Scheduler Thread #21/ERROR]: [io.papermc.paper.threadedregions.TickRegionScheduler] Region #2052 centered at chunk [3361, 1506] in world 'oneblock' failed to tick:
net.minecraft.ReportedException: Exception ticking world
    at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1820) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
    at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
    at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1647) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
    at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:407) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
    at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
    at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
    at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException
[19:20:52] [Region shutdown thread/INFO]: [RegionShutdownThread] Awaiting scheduler termination for 60s
[19:20:52] [Region shutdown thread/INFO]: [RegionShutdownThread] Scheduler halted
[19:20:52] [Region shutdown thread/INFO]: Stopping server
```

### Plugin and Datapack List

No datapacks, all +100 custom plugins (can't post this here).

### Actions to reproduce (if known)

I asked to players who own the region what they do just before the crash, they was AFK or just open crates.

### Folia version

Folia 1.20.4 e97b1ee version

**Comment by Press22300** [comment]
After updated to the latest version, we get the same issue

**Comment by electronicboy** [comment]
The actual cause exception is missing, try running with `-XX:-OmitStackTraceInFastThrow`

**Comment by Press22300** [comment]
[03:24:43] [Region Scheduler Thread #18/ERROR]: [io.papermc.paper.threadedregions.TickRegionScheduler] Region #71730 centered at chunk [-1799, -250] in world 'oneblock' failed to tick:
net.minecraft.ReportedException: Exception ticking world
    at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1830) ~[folia-1.20.4.jar:git-Folia-"ef2c697"]
    at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[folia-1.20.4.jar:git-Folia-"ef2c697"]
    at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1657) ~[folia-1.20.4.jar:git-Folia-"ef2c697"]
    at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:407) ~[folia-1.20.4.jar:git-Folia-"ef2c697"]
    at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[folia-1.20.4.jar:git-Folia-"ef2c697"]
    at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.4.jar:git-Folia-"ef2c697"]
    at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 10
    at java.util.ArrayList.add(ArrayList.java:455) ~[?:?]
    at java.util.ArrayList.add(ArrayList.java:467) ~[?:?]
    at net.minecraft.world.entity.player.Inventory.onOpen(Inventory.java:70) ~[?:?]
    at net.minecraft.world.inventory.AbstractContainerMenu.transferTo(AbstractContainerMenu.java:88) ~[?:?]
    at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1627) ~[folia-1.20.4.jar:git-Folia-"ef2c697"]
    at net.minecraft.server.level.ServerPlayer.closeContainer(ServerPlayer.java:2105) ~[?:?]
    at net.minecraft.server.players.PlayerList.remove(PlayerList.java:707) ~[folia-1.20.4.jar:git-Folia-"ef2c697"]
    at net.minecraft.server.network.ServerGamePacketListenerImpl.removePlayerFromWorld(ServerGamePacketListenerImpl.java:2143) ~[?:?]
    at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2121) ~[?:?]
    at net.minecraft.server.network.ServerCommonPacketListenerImpl.disconnect(ServerCommonPacketListenerImpl.java:332) ~[folia-1.20.4.jar:git-Folia-"ef2c697"]
    at net.minecraft.server.network.ServerCommonPacketListenerImpl.disconnect(ServerCommonPacketListenerImpl.java:298) ~[folia-1.20.4.jar:git-Folia-"ef2c697"]
    at net.minecraft.world.level.Level.guardEntityTick(Level.java:1378) ~[?:?]
    at net.minecraft.server.level.ServerLevel.lambda$tick$8(ServerLevel.java:1010) ~[?:?]
    at io.papermc.paper.threadedregions.RegionizedWorldData.forEachTickingEntity(RegionizedWorldData.java:620) ~[folia-1.20.4.jar:git-Folia-"ef2c697"]
    at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:989) ~[?:?]
    at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1818) ~[folia-1.20.4.jar:git-Folia-"ef2c697"]
    ... 6 more

**Comment by Press22300** [comment]
Got it !

**Comment by electronicboy** [comment]
user reported on discord that their server is using patches in order to load unsupported plugins into their environment
