### ISSUE TITLE
server crash on start

### ISSUE THREAD

**Issue by xKumorio** [PaperMC/Folia#226]
### Stack trace

[12:16:30 INFO]: Preparing start region for dimension minecraft:overworld
[12:16:30 ERROR]: Encountered an unexpected exception
java.lang.IllegalArgumentException: Source: 78
        at io.papermc.paper.chunk.system.scheduling.ThreadedTicketLevelPropagator.setSource(ThreadedTicketLevelPropagator.java:42) ~[folia-1.20.6.jar:1.20.6-DEV-78f49e0]
        at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.updateTicketLevel(ChunkHolderManager.java:568) ~[folia-1.20.6.jar:1.20.6-DEV-78f49e0]
        at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.addTicketAtLevel(ChunkHolderManager.java:664) ~[folia-1.20.6.jar:1.20.6-DEV-78f49e0]
        at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.addTicketAtLevel(ChunkHolderManager.java:623) ~[folia-1.20.6.jar:1.20.6-DEV-78f49e0]
        at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.addTicketAtLevel(ChunkHolderManager.java:578) ~[folia-1.20.6.jar:1.20.6-DEV-78f49e0]
        at net.minecraft.server.level.DistanceManager.addRegionTicketAtDistance(DistanceManager.java:105) ~[?:?]
        at net.minecraft.server.level.DistanceManager.addRegionTicket(DistanceManager.java:101) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.addRegionTicket(ServerChunkCache.java:730) ~[?:?]
        at net.minecraft.server.level.ServerLevel.setDefaultSpawnPos(ServerLevel.java:2388) ~[?:?]
        at net.minecraft.server.MinecraftServer.prepareLevels(MinecraftServer.java:857) ~[folia-1.20.6.jar:1.20.6-DEV-78f49e0]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:700) ~[folia-1.20.6.jar:1.20.6-DEV-78f49e0]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:464) ~[folia-1.20.6.jar:1.20.6-DEV-78f49e0]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[folia-1.20.6.jar:1.20.6-DEV-78f49e0]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1221) ~[folia-1.20.6.jar:1.20.6-DEV-78f49e0]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:350) ~[folia-1.20.6.jar:1.20.6-DEV-78f49e0]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[12:16:31 ERROR]: This crash report has been saved to: /server/6g6s/./crash-reports/crash-2024-05-26_12.16.31-server.txt

### Plugin and Datapack List

-

### Actions to reproduce (if known)

start server

### Folia version

latest dev build

### Other

-

**Comment by Warriorrrr** [comment]
https://github.com/PaperMC/Paper/issues/10790
