### ISSUE TITLE
Villagers cannot go through nether portals

### ISSUE THREAD

**Issue by kugge** [PaperMC/Folia#23]
### Expected behavior

Villagers should be able to travel through nether portals, like other mobs.

### Observed/Actual behavior

When I villager travel through a nether portal, it disappear and this error is throw:

```
[01:47:02 ERROR]: Entity threw exception at world:440.64865656939077,69.0,-206.24489705607485
net.minecraft.ReportedException: Loading entity NBT
        at net.minecraft.world.entity.Entity.load(Entity.java:2502) ~[folia-1.19.4.jar:git-Folia-"ed7a5c5"]
        at net.minecraft.world.entity.Entity.restoreFrom(Entity.java:3408) ~[folia-1.19.4.jar:git-Folia-"ed7a5c5"]
        at net.minecraft.world.entity.Entity.transformForAsyncTeleport(Entity.java:3696) ~[folia-1.19.4.jar:git-Folia-"ed7a5c5"]
        at net.minecraft.world.entity.Entity.portalToAsync(Entity.java:4108) ~[folia-1.19.4.jar:git-Folia-"ed7a5c5"]
        at net.minecraft.world.entity.Entity.netherPortalLogicAsync(Entity.java:3872) ~[folia-1.19.4.jar:git-Folia-"ed7a5c5"]
        at net.minecraft.world.entity.Entity.tryNetherPortal(Entity.java:3838) ~[folia-1.19.4.jar:git-Folia-"ed7a5c5"]
        at net.minecraft.world.entity.Entity.doPortalLogic(Entity.java:3801) ~[folia-1.19.4.jar:git-Folia-"ed7a5c5"]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1322) ~[?:?]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:965) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$8(ServerLevel.java:794) ~[?:?]
        at io.papermc.paper.threadedregions.RegionizedWorldData.forEachTickingEntity(RegionizedWorldData.java:519) ~[folia-1.19.4.jar:git-Folia-"ed7a5c5"]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:773) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1697) ~[folia-1.19.4.jar:git-Folia-"ed7a5c5"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[folia-1.19.4.jar:git-Folia-"ed7a5c5"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1542) ~[folia-1.19.4.jar:git-Folia-"ed7a5c5"]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:316) ~[folia-1.19.4.jar:git-Folia-"ed7a5c5"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:379) ~[folia-1.19.4.jar:git-Folia-"ed7a5c5"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:516) ~[folia-1.19.4.jar:git-Folia-"ed7a5c5"]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.IllegalStateException: World mismatch: expected world_nether but got world
        at net.minecraft.world.level.Level.getCurrentWorldData(Level.java:283) ~[?:?]
        at net.minecraft.world.level.Level.getGameTime(Level.java:1286) ~[?:?]
        at net.minecraft.world.entity.ai.Brain.stopAll(Brain.java:415) ~[?:?]
        at net.minecraft.world.entity.npc.Villager.refreshBrain(Villager.java:177) ~[?:?]
        at net.minecraft.world.entity.npc.Villager.readAdditionalSaveData(Villager.java:585) ~[?:?]
        at net.minecraft.world.entity.Entity.load(Entity.java:2400) ~[folia-1.19.4.jar:git-Folia-"ed7a5c5"]
        ... 18 more

```

### Steps/models to reproduce

1. Build a nether portal
2. Push a villager inside the nether portal. 
3. The villager disappears and an error is throw.

### Plugin and Datapack List

`> plugins
[01:48:50 INFO]: Server Plugins (0):`

### Folia version

```
> version
[01:49:18 INFO]: Checking version, please wait...
[01:49:19 INFO]: This server is running Folia version git-Folia-"ed7a5c5" (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: ed7a5c5)
You are running the latest version
```

**Comment by Machine-Maker** [comment]
Issue is that the new entity is created for the nether world, but this happens on the region thread for the old entity (somewhere in the overworld). So when the new entity goes to access the game time for brain logic, it think's its an illegal access of some overworld region game time from the nether.
