### ISSUE TITLE
Error on player login : java.lang.IllegalStateException: Player is already removed from player chunk loader

### ISSUE THREAD

**Issue by FunixG** [PaperMC/Folia#241]
### Stack trace

```
pacifista-hub               | [18:11:41 INFO]: [PermissionHandler] Le joueur FunixGaming a été configuré avec les roles : Admin, Légendaire, Joueur
pacifista-hub               | [18:11:41 ERROR]: Could not pass event PlayerJoinEvent to PacifistaMain v1.0.0
pacifista-hub               | java.lang.IllegalStateException: Player is already removed from player chunk loader
pacifista-hub               |   at io.papermc.paper.chunk.system.RegionizedPlayerChunkLoader.removePlayer(RegionizedPlayerChunkLoader.java:238) ~[folia-1.20.6.jar:1.20.6-DEV-36e5e83]
pacifista-hub               |   at net.minecraft.server.level.ChunkMap.removePlayerFromDistanceMaps(ChunkMap.java:167) ~[folia-1.20.6.jar:1.20.6-DEV-36e5e83]
pacifista-hub               |   at net.minecraft.server.level.ChunkMap.updatePlayerStatus(ChunkMap.java:988) ~[folia-1.20.6.jar:1.20.6-DEV-36e5e83]
pacifista-hub               |   at net.minecraft.server.level.ChunkMap.removeEntity(ChunkMap.java:1082) ~[folia-1.20.6.jar:1.20.6-DEV-36e5e83]
pacifista-hub               |   at net.minecraft.server.level.ServerChunkCache.removeEntity(ServerChunkCache.java:750) ~[?:?]
pacifista-hub               |   at net.minecraft.server.level.ServerLevel$EntityCallbacks.onTrackingEnd(ServerLevel.java:3023) ~[?:?]
pacifista-hub               |   at net.minecraft.server.level.ServerLevel$EntityCallbacks.b(ServerLevel.java:2903) ~[?:?]
pacifista-hub               |   at io.papermc.paper.chunk.system.entity.EntityLookup.entityStatusChange(EntityLookup.java:304) ~[folia-1.20.6.jar:1.20.6-DEV-36e5e83]
pacifista-hub               |   at io.papermc.paper.chunk.system.entity.EntityLookup$EntityCallback.a(EntityLookup.java:916) ~[folia-1.20.6.jar:1.20.6-DEV-36e5e83]
pacifista-hub               |   at net.minecraft.world.entity.Entity.setRemoved(Entity.java:5664) ~[folia-1.20.6.jar:1.20.6-DEV-36e5e83]
pacifista-hub               |   at net.minecraft.world.entity.Entity.remove(Entity.java:752) ~[folia-1.20.6.jar:1.20.6-DEV-36e5e83]
pacifista-hub               |   at net.minecraft.world.entity.LivingEntity.remove(LivingEntity.java:815) ~[?:?]
pacifista-hub               |   at net.minecraft.world.entity.player.Player.remove(Player.java:1527) ~[?:?]
pacifista-hub               |   at net.minecraft.server.level.ServerLevel.removePlayerImmediately(ServerLevel.java:1939) ~[?:?]
pacifista-hub               |   at net.minecraft.server.level.ServerPlayer.transformForAsyncTeleport(ServerPlayer.java:1543) ~[?:?]
pacifista-hub               |   at net.minecraft.server.level.ServerPlayer.transformForAsyncTeleport(ServerPlayer.java:199) ~[?:?]
pacifista-hub               |   at net.minecraft.world.entity.Entity.teleportAsync(Entity.java:4083) ~[folia-1.20.6.jar:1.20.6-DEV-36e5e83]
pacifista-hub               |   at org.bukkit.craftbukkit.entity.CraftEntity.lambda$teleportAsync$2(CraftEntity.java:1054) ~[?:?]
pacifista-hub               |   at org.bukkit.craftbukkit.entity.CraftEntity.teleportAsync(CraftEntity.java:1069) ~[?:?]
pacifista-hub               |   at org.bukkit.entity.Entity.teleportAsync(Entity.java:213) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:?]
pacifista-hub               |   at org.bukkit.entity.Entity.teleportAsync(Entity.java:200) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:?]
pacifista-hub               |   at PacifistaMain.jar/fr.pacifista.plugins.modules.essentials.spawn.events.SpawnPlayerEvents.onPlayerJoinEvent(SpawnPlayerEvents.java:24) ~[PacifistaMain.jar:?]
pacifista-hub               |   at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor22.execute(Unknown Source) ~[?:?]
pacifista-hub               |   at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:?]
pacifista-hub               |   at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-DEV-36e5e83]
pacifista-hub               |   at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:?]
pacifista-hub               |   at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[folia-1.20.6.jar:1.20.6-DEV-36e5e83]
pacifista-hub               |   at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[folia-1.20.6.jar:1.20.6-DEV-36e5e83]
pacifista-hub               |   at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:627) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:?]
pacifista-hub               |   at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:440) ~[folia-1.20.6.jar:1.20.6-DEV-36e5e83]
pacifista-hub               |   at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.lambda$handleConfigurationFinished$2(ServerConfigurationPacketListenerImpl.java:183) ~[folia-1.20.6.jar:1.20.6-DEV-36e5e83]
pacifista-hub               |   at io.papermc.paper.threadedregions.RegionizedTaskQueue$PrioritisedQueue$ChunkBasedPriorityTask.executeInternal(RegionizedTaskQueue.java:504) ~[folia-1.20.6.jar:1.20.6-DEV-36e5e83]
pacifista-hub               |   at io.papermc.paper.threadedregions.RegionizedTaskQueue$PrioritisedQueue.executeTask(RegionizedTaskQueue.java:434) ~[folia-1.20.6.jar:1.20.6-DEV-36e5e83]
pacifista-hub               |   at io.papermc.paper.threadedregions.RegionizedTaskQueue$RegionTaskQueueData.drainTasks(RegionizedTaskQueue.java:263) ~[folia-1.20.6.jar:1.20.6-DEV-36e5e83]
pacifista-hub               |   at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1676) ~[folia-1.20.6.jar:1.20.6-DEV-36e5e83]
pacifista-hub               |   at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:407) ~[folia-1.20.6.jar:1.20.6-DEV-36e5e83]
pacifista-hub               |   at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[folia-1.20.6.jar:1.20.6-DEV-36e5e83]
pacifista-hub               |   at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.6.jar:1.20.6-DEV-36e5e83]
pacifista-hub               |   at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
pacifista-hub               | [18:11:41 INFO]: FunixGaming[/172.18.0.1:38358] logged in with entity id 3955 at ([world]-1666.0, 64.0, 1.0)
```

### Plugin and Datapack List

No plugins (only custom plugins)

### Actions to reproduce (if known)

Randomly occurs when log in. When I log out after the stack trace and i try to log in I can't, I am forced to delete the playerdata folder or the player file to log in

### Folia version

This server is running Folia version 1.20.6-DEV-master@36e5e83 (2024-06-08T06:01:56Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
You are 1 version(s) behind
Download the new version at: https://papermc.io/downloads/paper

**Comment by electronicboy** [comment]
Teleporting players inside of the PlayerJoinEvent is unsupported behaviour
