### ISSUE TITLE
Call getNewScoreboard() returns excepcion

### ISSUE THREAD

**Issue by ricsal1** [PaperMC/Folia#25]
### Expected behavior

Create new Scoreboard with success

### Observed/Actual behavior

a null excepcion

[13:00:18 INFO]: [CoolProtection] [STDOUT] debug has ScoreboardManager org.bukkit.craftbukkit.v1_19_R3.scoreboard.CraftScoreboardManager@233c4975
[13:00:18 INFO]: [CoolProtection] [STDOUT] AsyncPlayerChatEvent
[13:00:18 ERROR]: Could not pass event ServerTickEndEvent to CoolProtection v1.6
java.lang.UnsupportedOperationException: null
        at org.bukkit.craftbukkit.v1_19_R3.scoreboard.CraftScoreboardManager.getNewScoreboard(CraftScoreboardManager.java:45) ~[folia-1.19.4.jar:git-Folia-"7072994"]
        at org.bukkit.craftbukkit.v1_19_R3.scoreboard.CraftScoreboardManager.getNewScoreboard(CraftScoreboardManager.java:25) ~[folia-1.19.4.jar:git-Folia-"7072994"]
        at me.tontito.coolprotection.TpsCheck.setScoreBoard(TpsCheck.java:399) ~[CoolProtection.jar:?]

### Steps/models to reproduce

CODE: 
ScoreboardManager manage = Bukkit.getScoreboardManager();

        if (manage == null) {
            System.out.println("debug doesnt' have ScoreboardManager");
            return;
        } else {
            System.out.println("debug has ScoreboardManager " + manage);
        }

        System.out.println("AsyncPlayerChatEvent");

        Scoreboard board = manage.getNewScoreboard();

RESULT:
[13:00:18 INFO]: [CoolProtection] [STDOUT] debug has ScoreboardManager org.bukkit.craftbukkit.v1_19_R3.scoreboard.CraftScoreboardManager@233c4975
[13:00:18 INFO]: [CoolProtection] [STDOUT] AsyncPlayerChatEvent
[13:00:18 ERROR]: Could not pass event ServerTickEndEvent to CoolProtection v1.6
java.lang.UnsupportedOperationException: null
        at org.bukkit.craftbukkit.v1_19_R3.scoreboard.CraftScoreboardManager.getNewScoreboard(CraftScoreboardManager.java:45) ~[folia-1.19.4.jar:git-Folia-"7072994"]
        at org.bukkit.craftbukkit.v1_19_R3.scoreboard.CraftScoreboardManager.getNewScoreboard(CraftScoreboardManager.java:25) ~[folia-1.19.4.jar:git-Folia-"7072994"]
        at me.tontito.coolprotection.TpsCheck.setScoreBoard(TpsCheck.java:399) ~[CoolProtection.jar:?]

### Plugin and Datapack List

No datapack.
One plugin been changed for folia compatibility

### Folia version

[13:03:13 INFO]: Checking version, please wait...
[13:03:13 INFO]: This server is running Folia version git-Folia-"7072994" (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 7072994)
You are running the latest version
Previous version: git-Folia-"00cfbaa" (MC: 1.19.4)

**Comment by powercasgamer** [comment]
https://github.com/PaperMC/Folia#current-broken-api
