### ISSUE TITLE
Server Crashed: NullPointerException

### ISSUE THREAD

**Issue by RitaSister** [PaperMC/Folia#253]
### Stack trace

[11:43:43] [Region Scheduler Thread #2/ERROR]: [io.papermc.paper.threadedregions.TickRegionScheduler] Region #2 centered at chunk [5, -2] in world 'world' failed to tick:
net.minecraft.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1901) ~[folia-1.21.jar:1.21-DEV-388cdac]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[folia-1.21.jar:1.21-DEV-388cdac]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1722) ~[folia-1.21.jar:1.21-DEV-388cdac]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:407) ~[folia-1.21.jar:1.21-DEV-388cdac]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:409) ~[folia-1.21.jar:1.21-DEV-388cdac]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:540) ~[folia-1.21.jar:1.21-DEV-388cdac]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot read field "chunk" because "chunkproviderserver_a" is null
	at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:520) ~[folia-1.21.jar:1.21-DEV-388cdac]
	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:413) ~[folia-1.21.jar:1.21-DEV-388cdac]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:768) ~[folia-1.21.jar:1.21-DEV-388cdac]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1894) ~[folia-1.21.jar:1.21-DEV-388cdac]
	... 6 more

### Plugin and Datapack List

[11:46:55 INFO]: Server Plugins (41):
[11:46:55 INFO]: Paper Plugins:
[11:46:55 INFO]:  - CarbonChat, FancyNpcs, FoliaWorldLoader
[11:46:55 INFO]: Bukkit Plugins:
[11:46:55 INFO]:  - ArmorStandEditor, AutoWhitelistRemove, BreweryX, CoreProtect, CoreProtectTNT, Craftorithm, DeluxeMenus, Essentials, EssentialsSpawn, GSit
[11:46:55 INFO]:  HeadDatabase, InventoryRollbackPlus, InvisibleFrames, InvSeePlusPlus, JoinMessenger, LiteBans, LuckPerms, Maintenance, Mclogs, NBTAPI
[11:46:55 INFO]:  NewbieFilter, OreAnnouncer, PlaceholderAPI, PlasmoVoice, PlayerHeads, ProtocolLib, pv-addon-discs, pv-addon-groups, pv-addon-lavaplayer-lib, pv-addon-sculk
[11:46:55 INFO]:  pv-addon-spectator, squaremap, squaremarker, TAB, TWSAdmin, TWSCheck, UltimateAutoRestart, Vault

### Folia version

[11:46:46 INFO]: Checking version, please wait...
[11:46:46 INFO]: This server is running Folia version 1.21-DEV-dev/1.21@388cdac (2024-07-31T04:54:34Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.20.6-DEV-d797082 (MC: 1.20.6)

**Comment by ocelotpotpie** [comment]
The 1.21 branch has just been created. There are likely to be issues. Please be patient, and do not open Github issues for stack traces on brand new dev branches.

**Comment by Spottedleaf** [comment]
https://github.com/PaperMC/Folia/commit/13e53730763b1d6470882e8c7a6803dc8a45ce12

**Comment by RitaSister** [comment]
> [13e5373](https://github.com/PaperMC/Folia/commit/13e53730763b1d6470882e8c7a6803dc8a45ce12)

thanks you for fixing and smart :) enjoy
