### ISSUE TITLE
Server Crashed: java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by kerudion** [PaperMC/Folia#254]
### Stack trace

```
[19:11:47] [Region Scheduler Thread #7/ERROR]: [io.papermc.paper.threadedregions.TickRegionScheduler] Region #1410 centered at chunk [-167, -34] in world 'world' failed to tick:
java.lang.ArrayIndexOutOfBoundsException: Index 6 out of bounds for length 5
	at me.lucko.spark.paper.common.monitor.tick.SparkTickStatistics$TpsRollingAverage.add(SparkTickStatistics.java:181) ~[spark-paper-1.10.84-20240720.204128-1.jar:?]
	at me.lucko.spark.paper.common.monitor.tick.SparkTickStatistics.onTick(SparkTickStatistics.java:88) ~[spark-paper-1.10.84-20240720.204128-1.jar:?]
	at me.lucko.spark.paper.common.tick.AbstractTickHook.onTick(AbstractTickHook.java:33) ~[spark-paper-1.10.84-20240720.204128-1.jar:?]
	at me.lucko.spark.paper.PaperTickHook.onTick(PaperTickHook.java:43) ~[spark-paper-1.10.84-20240720.204128-1.jar:?]
	at me.lucko.spark.paper.PaperSparkPlugin.onServerTickStart(PaperSparkPlugin.java:96) ~[spark-paper-1.10.84-20240720.204128-1.jar:?]
	at io.papermc.paper.SparksFly.tickStart(SparksFly.java:147) ~[folia-1.21.jar:1.21-DEV-13e5373]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1676) ~[folia-1.21.jar:1.21-DEV-13e5373]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:407) ~[folia-1.21.jar:1.21-DEV-13e5373]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:409) ~[folia-1.21.jar:1.21-DEV-13e5373]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:540) ~[folia-1.21.jar:1.21-DEV-13e5373]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[19:11:47] [Region shutdown thread/INFO]: [RegionShutdownThread] Awaiting scheduler termination for 60s
[19:11:47] [Region shutdown thread/INFO]: [RegionShutdownThread] Scheduler halted
[19:11:47] [Region shutdown thread/INFO]: Stopping server
```

Another one:
```
[19:20:49 ERROR]: [io.papermc.paper.threadedregions.TickRegionScheduler] Region #1135 centered at chunk [204, 125] in world 'world' failed to tick:
java.lang.ArrayIndexOutOfBoundsException: Index 5 out of bounds for length 5
        at me.lucko.spark.paper.common.monitor.tick.SparkTickStatistics$TpsRollingAverage.add(SparkTickStatistics.java:181) ~[spark-paper-1.10.84-20240720.204128-1.jar:?]
        at me.lucko.spark.paper.common.monitor.tick.SparkTickStatistics.onTick(SparkTickStatistics.java:88) ~[spark-paper-1.10.84-20240720.204128-1.jar:?]
        at me.lucko.spark.paper.common.tick.AbstractTickHook.onTick(AbstractTickHook.java:33) ~[spark-paper-1.10.84-20240720.204128-1.jar:?]
        at me.lucko.spark.paper.PaperTickHook.onTick(PaperTickHook.java:43) ~[spark-paper-1.10.84-20240720.204128-1.jar:?]
        at me.lucko.spark.paper.PaperSparkPlugin.onServerTickStart(PaperSparkPlugin.java:96) ~[spark-paper-1.10.84-20240720.204128-1.jar:?]
        at io.papermc.paper.SparksFly.tickStart(SparksFly.java:147) ~[folia-1.21.jar:1.21-DEV-13e5373]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1676) ~[folia-1.21.jar:1.21-DEV-13e5373]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:407) ~[folia-1.21.jar:1.21-DEV-13e5373]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:409) ~[folia-1.21.jar:1.21-DEV-13e5373]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:540) ~[folia-1.21.jar:1.21-DEV-13e5373]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[19:20:49] [Region shutdown thread/INFO]: [RegionShutdownThread] Awaiting scheduler termination for 60s
[19:20:49] [Region shutdown thread/INFO]: [RegionShutdownThread] Scheduler halted
[19:20:49] [Region shutdown thread/INFO]: Stopping server
```

### Plugin and Datapack List

[19:16:13 INFO]: Server Plugins (31):
[19:16:13 INFO]: Bukkit Plugins:
[19:16:13 INFO]:  - AntiPopup, armorstandtools, CommandAPI, CoreProtect, DiscordSRV, DiscordSRVUtils, emotecraft, emotes_command_extension, GSit
[19:16:13 INFO]: LibertyBans, LuckPerms, Maintenance, NBTAPI, PlaceholderAPI, Plan, PlasmoVoice, ProtocolLib, pv-addon-discs
[19:16:13 INFO]:  pv-addon-lavaplayer-lib, SkinsRestorer, TAB, TabCompleteFilter, ViaVersion
[19:16:13 INFO]:  WorldEdit

### Folia version

[19:15:47 INFO]: This server is running Folia version 1.21-DEV-dev/1.21@13e5373 (2024-07-31T15:49:20Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-DEV-388cdac (MC: 1.21)

**Comment by hir0say** [comment]
![image](https://github.com/user-attachments/assets/bd3f24af-2fd7-4e1b-a3e4-75fad19b755b)
The same problem. The reason for the appearance is not known.

**Comment by TheAmazingAnimal** [comment]
![Скриншот 31-07-2024 205211](https://github.com/user-attachments/assets/3100653f-ee56-4ef7-a773-e5b6e6dbe394)
Same. :(

**Comment by RitaSister** [comment]
lucko spark when is integrated in paper doesn't fully support folia, so you just can disable sparkl in paper config for fix this issues for while-time

**Comment by TATA82** [comment]
https://github.com/PaperMC/Folia/issues/253

**Comment by Kadeluxe** [comment]
> #253

It's different.

**Comment by electronicboy** [comment]
No, it's an entirely different error. First one is some internal fields relating to ticking, this is spark

**Comment by TATA82** [comment]
Sorry! Ok

**Comment by Spottedleaf** [comment]
https://github.com/PaperMC/Folia/commit/61dcc07256e1dfeb89bc77c826779699a9fd331a
