### ISSUE TITLE
Scheduled tasks cannot add potion effects

### ISSUE THREAD

**Issue by Aroshold** [PaperMC/Folia#259]
### Expected behavior

Players get effects from scheduled task via my custom plugin

### Observed/Actual behavior

Effects did not apply and the console logged an error
`
Cannot add effects to entities asynchronously
        at ca.spottedleaf.moonrise.common.util.TickThread.ensureTickThread(TickThread.java:59) ~[folia-1.21.jar:1.21-DEV-2b8c879]
        at net.minecraft.world.entity.LivingEntity.addEffect(LivingEntity.java:1167) ~[folia-1.21.jar:1.21-DEV-2b8c879]
        at net.minecraft.world.entity.LivingEntity.addEffect(LivingEntity.java:1162) ~[folia-1.21.jar:1.21-DEV-2b8c879]
        at net.minecraft.world.entity.LivingEntity.addEffect(LivingEntity.java:1153) ~[folia-1.21.jar:1.21-DEV-2b8c879]
        at org.bukkit.craftbukkit.entity.CraftLivingEntity.addPotionEffect(CraftLivingEntity.java:536) ~[folia-1.21.jar:1.21-DEV-2b8c879]
        at org.bukkit.craftbukkit.entity.CraftLivingEntity.addPotionEffect(CraftLivingEntity.java:530) ~[folia-1.21.jar:1.21-DEV-2b8c879]
        at acontents-3.11-RELEASE.jar/net.aroshold.acontents.tasks.RunnableTasks$3.run(RunnableTasks.java:96) ~[acontents-3.11-RELEASE.jar:?]
        at acontents-3.11-RELEASE.jar/net.aroshold.acontents.util.UltimateScheduler.lambda$runTimer$1(UltimateScheduler.java:27) ~[acontents-3.11-RELEASE.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179) ~[folia-1.21.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37) ~[folia-1.21.jar:?]
        at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:293) ~[folia-1.21.jar:1.21-DEV-2b8c879]
        at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:148) ~[folia-1.21.jar:1.21-DEV-2b8c879]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:409) ~[folia-1.21.jar:1.21-DEV-2b8c879]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:540) ~[folia-1.21.jar:1.21-DEV-2b8c879]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
`

### Steps/models to reproduce

Create a simple plugin that schedules adding potion effects to players using folia's scheduler and make it folia-compatible.

### Plugin and Datapack List

ArosholdContents, Chunky, ChunkyBorder, ClansLite, CoreProtect, DiscordSRV, GSit, LuckPerms, Pl3xMap, PlaceholderAPI, PlasmoVoice, ProtocolLib, pv-addon-discs, pv-addon-lavaplayer-lib, SkinsRestorer, TAB.
No datapacks

### Folia version

1.21-DEV-dev/1.21@2b8c879 (2024-08-03T17:43:23Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

**Comment by electronicboy** [comment]
don't mutate entity state from the global scheduler
