### ISSUE TITLE
Folia1.21 chunk crashes, unable to run server normally

### ISSUE THREAD

**Issue by buildin1** [PaperMC/Folia#263]
### Expected behavior

I hope to fix this bug as soon as possible because it is really causing my server to malfunction

### Observed/Actual behavior

This is the crash log I captured, and every crash is a similar log

[20:03:16] [Region Scheduler Thread #4/ERROR]: [io.papermc.paper.threadedregions.TickRegionScheduler] Region #112963 centered at chunk [3043, 13069] in world 'world' failed to tick:
java.lang.IllegalStateException: Accessing entity state off owning region's thread
	at ca.spottedleaf.moonrise.common.util.TickThread.ensureTickThread(TickThread.java:59) ~[folia-1.21.jar:1.21-DEV-8e876b4]
	at org.bukkit.craftbukkit.entity.CraftTextDisplay.getHandle(CraftTextDisplay.java:25) ~[folia-1.21.jar:1.21-DEV-8e876b4]
	at org.bukkit.craftbukkit.entity.CraftTextDisplay.getHandle(CraftTextDisplay.java:10) ~[folia-1.21.jar:1.21-DEV-8e876b4]
	at org.bukkit.craftbukkit.entity.CraftEntity.isInsideVehicle(CraftEntity.java:602) ~[folia-1.21.jar:1.21-DEV-8e876b4]
	at org.bukkit.craftbukkit.entity.CraftEntity.getVehicle(CraftEntity.java:617) ~[folia-1.21.jar:1.21-DEV-8e876b4]
	at net.minecraft.world.entity.Entity.removePassenger(Entity.java:3226) ~[folia-1.21.jar:1.21-DEV-8e876b4]
	at net.minecraft.world.entity.Entity.removeVehicle(Entity.java:3180) ~[folia-1.21.jar:1.21-DEV-8e876b4]
	at net.minecraft.world.entity.Entity.stopRiding(Entity.java:3191) ~[folia-1.21.jar:1.21-DEV-8e876b4]
	at net.minecraft.world.entity.Entity.stopRiding(Entity.java:3187) ~[folia-1.21.jar:1.21-DEV-8e876b4]
	at net.minecraft.world.entity.Entity.ejectPassengers(Entity.java:3165) ~[folia-1.21.jar:1.21-DEV-8e876b4]
	at net.minecraft.server.level.ServerPlayer.disconnect(ServerPlayer.java:2492) ~[folia-1.21.jar:1.21-DEV-8e876b4]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.removePlayerFromWorld(ServerGamePacketListenerImpl.java:2088) ~[folia-1.21.jar:1.21-DEV-8e876b4]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2068) ~[folia-1.21.jar:1.21-DEV-8e876b4]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2055) ~[folia-1.21.jar:1.21-DEV-8e876b4]
	at net.minecraft.network.Connection.handleDisconnection(Connection.java:959) ~[folia-1.21.jar:1.21-DEV-8e876b4]
	at io.papermc.paper.threadedregions.RegionizedWorldData.tickConnections(RegionizedWorldData.java:498) ~[folia-1.21.jar:1.21-DEV-8e876b4]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1951) ~[folia-1.21.jar:1.21-DEV-8e876b4]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:475) ~[folia-1.21.jar:1.21-DEV-8e876b4]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1745) ~[folia-1.21.jar:1.21-DEV-8e876b4]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:407) ~[folia-1.21.jar:1.21-DEV-8e876b4]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:457) ~[folia-1.21.jar:1.21-DEV-8e876b4]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:546) ~[folia-1.21.jar:1.21-DEV-8e876b4]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

### Steps/models to reproduce

I haven't found a specific triggering method yet, but the probability of crashing during high-speed mapping will become higher

### Plugin and Datapack List

[21:03:15 INFO]: Paper Plugins:
[21:03:15 INFO]:  - HuskHomes
[21:03:15 INFO]: Bukkit Plugins:
[21:03:15 INFO]:  - ActivityRewarder, AllMusic3, AntiPopup, AxInventoryRestore, AxRankMenu, AxRewards, AxShulkers, BetterGUI, BetterRTP, BlockLocker
[21:03:15 INFO]:  BreweryX, CMI, CMILib, CoreProtect, Craftorithm, FKBoom, FoxViaRestore, FreedomChat, GlobalMarketPlus, GreenChunk
[21:03:15 INFO]:  GSit, HeadDrop, InvisibleFrames, InvSeePlusPlus, LiteBans, LuckPerms, MapModCompanion, Matrix, Mclogs, Orebfuscator
[21:03:15 INFO]:  PlaceholderAPI, PlayerGuild, PlayerTask, PlayerTitle, PlugManX, ProtocolLib, Residence, ResidenceInfo, SkinsRestorer, *SnowReports
[21:03:15 INFO]:  spark, SuperExpress, TAB, ToolStats, UseTranslatedNames, Vault, ViaBackwards, ViaRewind, ViaVersion, WorldEdit

### Folia version

[11:44:06 INFO]: This server is running Folia version 1.21-DEV-dev/1.21@2b8c879 (2024-08-05T03:04:53Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-DEV-2541ddf (MC: 1.21)

### Other

His crash frequency is very high, with an average probability of more than 3 crashes per 3 hours. The probability of triggering crashes during map running and TP transmission is even higher, and it is also possible to trigger crashes when using a new 1.21 record (probability is low, yet to be confirmed)

**Comment by ghost** [comment]
any news about this?

**Comment by Runkang10** [comment]
I recommend use Paper over Folia until it gets stable to use.

**Comment by ocelotpotpie** [comment]
This seems like it may be a plugin accessing something it shouldn't. If you can reliably reproduce in 1.21.11, please provide reproduction steps and another crash log and reopen the issue.
