### ISSUE TITLE
I'm trying craft any item

### ISSUE THREAD

**Issue by ImCryptixx** [PaperMC/Folia#273]
### Expected behavior

Well, everything had to be crafted

### Observed/Actual behavior

nothing was crafted

### Steps/models to reproduce

[06:33:33 ERROR]: Failed to handle packet net.minecraft.network.protocol.game.PacketPlayInWindowClick@69e6ff76, suppressing error
java.lang.IllegalArgumentException: Recipe cannot have an empty result
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
        at org.bukkit.inventory.CraftingRecipe.checkResult(CraftingRecipe.java:105) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.inventory.ShapelessRecipe.<init>(ShapelessRecipe.java:39) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.inventory.CraftShapelessRecipe.<init>(CraftShapelessRecipe.java:19) ~[?:?]
        at org.bukkit.craftbukkit.inventory.CraftShapelessRecipe.<init>(CraftShapelessRecipe.java:23) ~[?:?]
        at net.minecraft.world.item.crafting.ShapelessRecipe.toBukkitRecipe(ShapelessRecipe.java:42) ~[?:?]
        at net.minecraft.world.item.crafting.ShapelessRecipe.matches(ShapelessRecipe.java:22) ~[?:?]
        at net.minecraft.world.item.crafting.RecipeHolder.toBukkitRecipe(RecipeHolder.java:15) ~[folia-1.21.1.jar:1.21.1-DEV-e402f96]
        at org.bukkit.craftbukkit.inventory.CraftInventoryCrafting.getRecipe(CraftInventoryCrafting.java:120) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3173) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.a(ServerboundContainerClickPacket.java:33) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:58) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$2(PacketUtils.java:86) ~[?:?]
        at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:173) ~[folia-1.21.1.jar:1.21.1-DEV-e402f96]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1711) ~[folia-1.21.1.jar:1.21.1-DEV-e402f96]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:407) ~[folia-1.21.1.jar:1.21.1-DEV-e402f96]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:406) ~[folia-1.21.1.jar:1.21.1-DEV-e402f96]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:540) ~[folia-1.21.1.jar:1.21.1-DEV-e402f96]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

### Plugin and Datapack List

null

### Folia version

1.21.1

**Comment by ColdeZhang** [comment]
same here

**Comment by Kadeluxe** [comment]
Works for me

**Comment by MrHua269** [comment]
https://github.com/LuminolMC/Luminol/blob/dev/1.21.1/patches/api/0006-Try-fixing-folia-273.patch Might be helpful for this issue

**Comment by Kadeluxe** [comment]
> https://github.com/LuminolMC/Luminol/blob/dev/1.21.1/patches/api/0006-Try-fixing-folia-273.patch Might be helpful for this issue

No...

**Comment by balazskokai** [comment]
having same issue, really waiting for a fix

**Comment by balazskokai** [comment]
> > https://github.com/LuminolMC/Luminol/blob/dev/1.21.1/patches/api/0006-Try-fixing-folia-273.patch Might be helpful for this issue
> 
> No...

did you tried to complie whit that pach?

**Comment by Euphillya** [comment]
Next update upstream with Paper fix the problem.

**Comment by balazskokai** [comment]
> Next update upstream with Paper fix the problem.
> 
> https://github.com/PaperMC/Paper/blob/f97aff74b6f7fd4940c0c0b6cca3f8ac6e1afdef/patches/api/0469-Fix-issues-with-recipe-API.patch#L51C10-L51C105
> 
> This patch is not completely present on last upstream of Folia

okay, i will try to complie that branch and if that not works i will try to just only add that patch to master branch

**Comment by balazskokai** [comment]
> > Next update upstream with Paper fix the problem.
> > https://github.com/PaperMC/Paper/blob/f97aff74b6f7fd4940c0c0b6cca3f8ac6e1afdef/patches/api/0469-Fix-issues-with-recipe-API.patch#L51C10-L51C105
> > This patch is not completely present on last upstream of Folia
> 
> okay, i will try to complie that branch and if that not works i will try to just only add that patch to master branch
> 
> EDIT: realized thats papermc patch, so i will try to add it to foliamc as 0006 and complie it

I tried compliing but i alway getting this error:
Task :paper:prepareForDownstream

> Task :applyApiPatches FAILED
***   Please review above details and finish the apply then
***   save the changes with `./gradlew rebuildPatches`

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':applyApiPatches'.
Creating Folia-API from patch source...
Applying patches to Folia-API...
Applying: Force disable timings
> io.papermc.paperweight.PaperweightException: Failed to apply patches
Applying: Region scheduler API
Applying: Require plugins to be explicitly marked as Folia supported
Applying: Add RegionizedServerInitEvent
Applying: Add API for checking ownership of region by position/entity
Applying: Fix issues with recipe API
Patch failed at 0006 Fix issues with recipe API
error: invalid object 100644 1b7b0[77](https://github.com/balazskokai/folia_build_action/actions/runs/10366715544/job/28696587145#step:7:78)15067014bf3d35002ae1655793248b426 for 'src/main/java/org/bukkit/inventory/CraftingRecipe.java'
error: Repository lacks necessary blobs to fall back on 3-way merge.
hint: Use 'git am --show-current-patch=diff' to see the failed patch
hint: When you have resolved this problem, run "git am --continue".
hint: If you prefer to skip this patch, run "git am --skip" instead.
hint: To restore the original branch and stop patching, run "git am --abort".
hint: Disable this message with "git config advice.mergeConflict false"


Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.7/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
3 actionable tasks: 3 executed

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 4m 39s
Error: Process completed with exit code 1.

**Comment by MrHua269** [comment]
> > > Next update upstream with Paper fix the problem.
> > > https://github.com/PaperMC/Paper/blob/f97aff74b6f7fd4940c0c0b6cca3f8ac6e1afdef/patches/api/0469-Fix-issues-with-recipe-API.patch#L51C10-L51C105
> > > This patch is not completely present on last upstream of Folia
> > 
> > okay, i will try to complie that branch and if that not works i will try to just only add that patch to master branch
> > 
> > EDIT: realized thats papermc patch, so i will try to add it to foliamc as 0006 and complie it
> 
> I tried compliing but i alway getting this error:
> ```
> Task :paper:prepareForDownstream
> > Task :applyApiPatches FAILED
> ***   Please review above details and finish the apply then
> ***   save the changes with `./gradlew rebuildPatches`
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':applyApiPatches'.
> Creating Folia-API from patch source...
> Applying patches to Folia-API...
> Applying: Force disable timings
> > io.papermc.paperweight.PaperweightException: Failed to apply patches
> Applying: Region scheduler API
> Applying: Require plugins to be explicitly marked as Folia supported
> Applying: Add RegionizedServerInitEvent
> Applying: Add API for checking ownership of region by position/entity
> Applying: Fix issues with recipe API
> Patch failed at 0006 Fix issues with recipe API
> error: invalid object 100644 1b7b0[77](https://github.com/balazskokai/folia_build_action/actions/runs/10366715544/job/28696587145#step:7:78)15067014bf3d35002ae1655793248b426 for 'src/main/java/org/bukkit/inventory/CraftingRecipe.java'
> error: Repository lacks necessary blobs to fall back on 3-way merge.
> hint: Use 'git am --show-current-patch=diff' to see the failed patch
> hint: When you have resolved this problem, run "git am --continue".
> hint: If you prefer to skip this patch, run "git am --skip" instead.
> hint: To restore the original branch and stop patching, run "git am --abort".
> hint: Disable this message with "git config advice.mergeConflict false"
> 
> 
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
> 
> You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
> 
> For more on this, please refer to https://docs.gradle.org/8.7/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
> 3 actionable tasks: 3 executed
> 
> * Try:
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> > Get more help at https://help.gradle.org.
> 
> BUILD FAILED in 4m 39s
> Error: Process completed with exit code 1.
> ```

You should solve the conflict by yourself

**Comment by balazskokai** [comment]
> > > > Next update upstream with Paper fix the problem.
> > > > https://github.com/PaperMC/Paper/blob/f97aff74b6f7fd4940c0c0b6cca3f8ac6e1afdef/patches/api/0469-Fix-issues-with-recipe-API.patch#L51C10-L51C105
> > > > This patch is not completely present on last upstream of Folia
> > > 
> > > 
> > > okay, i will try to complie that branch and if that not works i will try to just only add that patch to master branch
> > > EDIT: realized thats papermc patch, so i will try to add it to foliamc as 0006 and complie it
> > 
> > 
> > I tried compliing but i alway getting this error:
> > ```
> > Task :paper:prepareForDownstream
> > > Task :applyApiPatches FAILED
> > ***   Please review above details and finish the apply then
> > ***   save the changes with `./gradlew rebuildPatches`
> > 
> > FAILURE: Build failed with an exception.
> > 
> > * What went wrong:
> > Execution failed for task ':applyApiPatches'.
> > Creating Folia-API from patch source...
> > Applying patches to Folia-API...
> > Applying: Force disable timings
> > > io.papermc.paperweight.PaperweightException: Failed to apply patches
> > Applying: Region scheduler API
> > Applying: Require plugins to be explicitly marked as Folia supported
> > Applying: Add RegionizedServerInitEvent
> > Applying: Add API for checking ownership of region by position/entity
> > Applying: Fix issues with recipe API
> > Patch failed at 0006 Fix issues with recipe API
> > error: invalid object 100644 1b7b0[77](https://github.com/balazskokai/folia_build_action/actions/runs/10366715544/job/28696587145#step:7:78)15067014bf3d35002ae1655793248b426 for 'src/main/java/org/bukkit/inventory/CraftingRecipe.java'
> > error: Repository lacks necessary blobs to fall back on 3-way merge.
> > hint: Use 'git am --show-current-patch=diff' to see the failed patch
> > hint: When you have resolved this problem, run "git am --continue".
> > hint: If you prefer to skip this patch, run "git am --skip" instead.
> > hint: To restore the original branch and stop patching, run "git am --abort".
> > hint: Disable this message with "git config advice.mergeConflict false"
> > 
> > 
> > Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
> > 
> > You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
> > 
> > For more on this, please refer to https://docs.gradle.org/8.7/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
> > 3 actionable tasks: 3 executed
> > 
> > * Try:
> > > Run with --stacktrace option to get the stack trace.
> > > Run with --info or --debug option to get more log output.
> > > Run with --scan to get full insights.
> > > Get more help at https://help.gradle.org.
> > 
> > BUILD FAILED in 4m 39s
> > Error: Process completed with exit code 1.
> > ```
> 
> You should solve the conflict by yourself

what conflict? an you tell me more?

**Comment by Euphillya** [comment]
https://github.com/PaperMC/Folia/compare/e402f963b5c4...053b04c7a154 Fix the problem
