### ISSUE TITLE
Problem with SuperVanish

### ISSUE THREAD

**Issue by dafm1n** [PaperMC/Folia#294]
### Expected behavior

The fact that the /vanish command will throw the player into invisibility

### Observed/Actual behavior

an error occurs with the region flow

### Steps/models to reproduce

sheduler

### Plugin and Datapack List

- CoreProtect, GSit, LuckPerms, PlasmoVoice, SuperVanish, TAB

### Folia version

This server is running Folia version 1.21.1-DEV-dev/1.21.1@88e0907 (2024-09-13T01:58:52Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version

**Comment by dafm1n** [comment]
[ca.spottedleaf.moonrise.common.util.TickThread] Thread Region Scheduler Thread #0 failed main thread check: Accessing entity state off owning region's thread
java.lang.Throwable: null
        at ca.spottedleaf.moonrise.common.util.TickThread.ensureTickThread(TickThread.java:58) ~[folia-1.21.1.jar:1.21.1-DEV-88e0907]
        at org.bukkit.craftbukkit.entity.CraftSkeleton.getHandle(CraftSkeleton.java:43) ~[folia-1.21.1.jar:1.21.1-DEV-88e0907]
        at org.bukkit.craftbukkit.entity.CraftSkeleton.getHandle(CraftSkeleton.java:7) ~[folia-1.21.1.jar:1.21.1-DEV-88e0907]
        at org.bukkit.craftbukkit.entity.CraftMob.getTarget(CraftMob.java:36) ~[folia-1.21.1.jar:1.21.1-DEV-88e0907]
        at org.bukkit.craftbukkit.entity.CraftMob.getTarget(CraftMob.java:14) ~[folia-1.21.1.jar:1.21.1-DEV-88e0907]
        at SuperVanish-6.2.20.jar/de.myzelyam.supervanish.visibility.VisibilityChanger.lambda$stopTarget$3(VisibilityChanger.java:113) ~[SuperVanish-6.2.20.jar:?]
        at SuperVanish-6.2.20.jar/de.myzelyam.supervanish.minelib.scheduler.common.util.task.FoliaTask.lambda$wrapRunnable$1(FoliaTask.java:46) ~[SuperVanish-6.2.20.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179) ~[folia-1.21.1.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37) ~[folia-1.21.1.jar:?]
        at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:293) ~[folia-1.21.1.jar:1.21.1-DEV-88e0907]
        at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:148) ~[folia-1.21.1.jar:1.21.1-DEV-88e0907]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:418) ~[folia-1.21.1.jar:1.21.1-DEV-88e0907]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:540) ~[folia-1.21.1.jar:1.21.1-DEV-88e0907]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[11:12:59 WARN]: [SuperVanish] Global task for SuperVanish v6.2.20 generated an exception
java.lang.IllegalStateException: Accessing entity state off owning region's thread
        at ca.spottedleaf.moonrise.common.util.TickThread.ensureTickThread(TickThread.java:59) ~[folia-1.21.1.jar:1.21.1-DEV-88e0907]
        at org.bukkit.craftbukkit.entity.CraftSkeleton.getHandle(CraftSkeleton.java:43) ~[folia-1.21.1.jar:1.21.1-DEV-88e0907]
        at org.bukkit.craftbukkit.entity.CraftSkeleton.getHandle(CraftSkeleton.java:7) ~[folia-1.21.1.jar:1.21.1-DEV-88e0907]
        at org.bukkit.craftbukkit.entity.CraftMob.getTarget(CraftMob.java:36) ~[folia-1.21.1.jar:1.21.1-DEV-88e0907]
        at org.bukkit.craftbukkit.entity.CraftMob.getTarget(CraftMob.java:14) ~[folia-1.21.1.jar:1.21.1-DEV-88e0907]
        at SuperVanish-6.2.20.jar/de.myzelyam.supervanish.visibility.VisibilityChanger.lambda$stopTarget$3(VisibilityChanger.java:113) ~[SuperVanish-6.2.20.jar:?]
        at SuperVanish-6.2.20.jar/de.myzelyam.supervanish.minelib.scheduler.common.util.task.FoliaTask.lambda$wrapRunnable$1(FoliaTask.java:46) ~[SuperVanish-6.2.20.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179) ~[folia-1.21.1.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37) ~[folia-1.21.1.jar:?]
        at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:293) ~[folia-1.21.1.jar:1.21.1-DEV-88e0907]
        at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:148) ~[folia-1.21.1.jar:1.21.1-DEV-88e0907]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:418) ~[folia-1.21.1.jar:1.21.1-DEV-88e0907]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:540) ~[folia-1.21.1.jar:1.21.1-DEV-88e0907]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by Warriorrrr** [comment]
This is not a folia issue, report this to the developers of the supervanish plugin
