### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by DevEtix** [PaperMC/Folia#298]
### Stack trace

Caught previously unhandled exception :
java.io.IOError: java.io.IOException: Input/output error
    at org.jline.keymap.BindingReader.readCharacter(BindingReader.java:170) ~[jline-reader-3.20.0.jar:?]
    at org.jline.keymap.BindingReader.readBinding(BindingReader.java:110) ~[jline-reader-3.20.0.jar:?]
    at org.jline.keymap.BindingReader.readBinding(BindingReader.java:61) ~[jline-reader-3.20.0.jar:?]
    at org.jline.reader.impl.LineReaderImpl.doReadBinding(LineReaderImpl.java:923) ~[jline-reader-3.20.0.jar:?]
    at org.jline.reader.impl.LineReaderImpl.readBinding(LineReaderImpl.java:956) ~[jline-reader-3.20.0.jar:?]
    at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:651) ~[jline-reader-3.20.0.jar:?]
    at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:468) ~[jline-reader-3.20.0.jar:?]
    at net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:158) ~[terminalconsoleappender-1.3.0.jar:?]
    at net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:141) ~[terminalconsoleappender-1.3.0.jar:?]
    at net.minecraft.server.dedicated.DedicatedServer$1.run(DedicatedServer.java:117) ~[folia-1.21.1.jar:1.21.1-DEV-06d719d]
Caused by: java.io.IOException: Input/output error
    at java.base/java.io.FileInputStream.read0(Native Method) ~[?:?]
    at java.base/java.io.FileInputStream.read(FileInputStream.java:231) ~[?:?]
    at org.jline.terminal.impl.AbstractPty$PtyInputStream.read(AbstractPty.java:73) ~[jline-terminal-3.21.0.jar:?]
    at org.jline.utils.NonBlockingInputStream.read(NonBlockingInputStream.java:62) ~[jline-terminal-3.21.0.jar:?]
    at org.jline.utils.NonBlocking$NonBlockingInputStreamReader.read(NonBlocking.java:168) ~[jline-terminal-3.21.0.jar:?]
    at org.jline.utils.NonBlockingReader.read(NonBlockingReader.java:57) ~[jline-terminal-3.21.0.jar:?]
    at org.jline.keymap.BindingReader.readCharacter(BindingReader.java:160) ~[jline-reader-3.20.0.jar:?]
    ... 9 more

### Plugin and Datapack List

Server crash idk why

### Actions to reproduce (if known)

idk

### Folia version

1.21.1-dev version

### Other

idk

**Comment by electronicboy** [comment]
Your terminal was killed; generally, either a "you forgot to run it in a multiplexor over ssh", or, was killed by the host
