### ISSUE TITLE
Piston move block may cause ghost block on Folia 1.21.3 and 1.21.4

### ISSUE THREAD

**Issue by xuancat0208** [PaperMC/Folia#302]
### Stack trace

```
[05:57:39] [Region Scheduler Thread #8/ERROR]: [ca.spottedleaf.moonrise.common.util.TickThread] Thread Region Scheduler Thread #8 failed main thread check: Cannot asynchronously load chunks
java.lang.Throwable: null
	at ca.spottedleaf.moonrise.common.util.TickThread.ensureTickThread(TickThread.java:51) ~[folia-1.21.3.jar:1.21.3-DEV-c937c72]
	at net.minecraft.server.level.ServerChunkCache.syncLoad(ServerChunkCache.java:100) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.getChunkFallback(ServerChunkCache.java:146) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.getChunk(ServerChunkCache.java:289) ~[?:?]
	at net.minecraft.world.level.Level.getChunk(Level.java:1094) ~[?:?]
	at net.minecraft.world.level.Level.getBlockState(Level.java:1395) ~[?:?]
	at net.minecraft.world.entity.Entity.checkInsideBlocks(Entity.java:1754) ~[folia-1.21.3.jar:1.21.3-DEV-c937c72]
	at net.minecraft.world.entity.Entity.applyEffectsFromBlocks(Entity.java:1367) ~[folia-1.21.3.jar:1.21.3-DEV-c937c72]
	at net.minecraft.world.entity.Entity.applyEffectsFromBlocks(Entity.java:1354) ~[folia-1.21.3.jar:1.21.3-DEV-c937c72]
	at net.minecraft.world.level.block.piston.PistonMovingBlockEntity.moveEntityByPiston(PistonMovingBlockEntity.java:206) ~[?:?]
	at net.minecraft.world.level.block.piston.PistonMovingBlockEntity.moveCollidedEntities(PistonMovingBlockEntity.java:186) ~[?:?]
	at net.minecraft.world.level.block.piston.PistonMovingBlockEntity.tick(PistonMovingBlockEntity.java:339) ~[?:?]
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.tick(LevelChunk.java:1087) ~[?:?]
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.tick(LevelChunk.java:1030) ~[?:?]
	at net.minecraft.world.level.Level.tickBlockEntities(Level.java:1520) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:844) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1981) ~[folia-1.21.3.jar:1.21.3-DEV-c937c72]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1803) ~[folia-1.21.3.jar:1.21.3-DEV-c937c72]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:407) ~[folia-1.21.3.jar:1.21.3-DEV-c937c72]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:418) ~[folia-1.21.3.jar:1.21.3-DEV-c937c72]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:546) ~[folia-1.21.3.jar:1.21.3-DEV-c937c72]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[05:57:39] [Region Scheduler Thread #8/ERROR]: BlockEntity threw exception at world:-21964,74,-18774
java.lang.IllegalStateException: Cannot asynchronously load chunks
	at ca.spottedleaf.moonrise.common.util.TickThread.ensureTickThread(TickThread.java:52) ~[folia-1.21.3.jar:1.21.3-DEV-c937c72]
	at net.minecraft.server.level.ServerChunkCache.syncLoad(ServerChunkCache.java:100) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.getChunkFallback(ServerChunkCache.java:146) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.getChunk(ServerChunkCache.java:289) ~[?:?]
	at net.minecraft.world.level.Level.getChunk(Level.java:1094) ~[?:?]
	at net.minecraft.world.level.Level.getBlockState(Level.java:1395) ~[?:?]
	at net.minecraft.world.entity.Entity.checkInsideBlocks(Entity.java:1754) ~[folia-1.21.3.jar:1.21.3-DEV-c937c72]
	at net.minecraft.world.entity.Entity.applyEffectsFromBlocks(Entity.java:1367) ~[folia-1.21.3.jar:1.21.3-DEV-c937c72]
	at net.minecraft.world.entity.Entity.applyEffectsFromBlocks(Entity.java:1354) ~[folia-1.21.3.jar:1.21.3-DEV-c937c72]
	at net.minecraft.world.level.block.piston.PistonMovingBlockEntity.moveEntityByPiston(PistonMovingBlockEntity.java:206) ~[?:?]
	at net.minecraft.world.level.block.piston.PistonMovingBlockEntity.moveCollidedEntities(PistonMovingBlockEntity.java:186) ~[?:?]
	at net.minecraft.world.level.block.piston.PistonMovingBlockEntity.tick(PistonMovingBlockEntity.java:339) ~[?:?]
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.tick(LevelChunk.java:1087) ~[?:?]
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.tick(LevelChunk.java:1030) ~[?:?]
	at net.minecraft.world.level.Level.tickBlockEntities(Level.java:1520) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:844) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1981) ~[folia-1.21.3.jar:1.21.3-DEV-c937c72]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1803) ~[folia-1.21.3.jar:1.21.3-DEV-c937c72]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:407) ~[folia-1.21.3.jar:1.21.3-DEV-c937c72]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:418) ~[folia-1.21.3.jar:1.21.3-DEV-c937c72]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:546) ~[folia-1.21.3.jar:1.21.3-DEV-c937c72]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Plugin and Datapack List

_none_

### Actions to reproduce (if known)

![](https://i.imgur.com/I9XGGlK.png)  
![](https://i.imgur.com/GBjUfJo.png)  
It's less likely to happen.

### Folia version

```
[08:40:15 INFO]: This server is running Folia version 1.21.3-DEV-dev/1.21.3@c937c72 (2024-11-30T21:50:31Z) (Implementing API version 1.21.3-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.3-DEV-88f8af4 (MC: 1.21.3)
```

### Other

This doesn't happen before Folia 1.21.1.

**Comment by Spottedleaf** [comment]
This may be a fix on 1.21.4: https://github.com/PaperMC/Folia/commit/94d65c398cf3015bafcaf46a09b2ea42cec66d24

If it still happens, please provide the world data

**Comment by MrHua269** [comment]
> This may be a fix on 1.21.4: [94d65c3](https://github.com/PaperMC/Folia/commit/94d65c398cf3015bafcaf46a09b2ea42cec66d24)
> 
> If it still happens, please provide the world data

Still happening

**Comment by ocelotpotpie** [comment]
> 
> Still happening

As asked, please provide a download of the world data so we can test/verify.

**Comment by MrHua269** [comment]
> > Still happening
> 
> As asked, please provide a download of the world data so we can test/verify.

[world.zip](https://github.com/user-attachments/files/18138926/world.zip)

**Comment by MsEDok** [comment]
I did have this problem i tested with fresh folia server no problem even when apply my server settings to it no problem.

The cause that i have kinda found to make that happen 100% all the time is that have the
Gamerule spawnChunkRadius 0

When set it to 0 and you fly away unloading the chunk with piston and the fly back to it and console spam with that error and it cause ghost block

When set the spawnchunk back to default 2 (i think) this problem havent happen again.

**Comment by MrHua269** [comment]
> I did have this problem i tested with fresh folia server no problem even when apply my server settings to it no problem.
> 
> The cause that i have kinda found to make that happen 100% all the time is that have the
> Gamerule spawnChunkRadius 0
> 
> When set it to 0 and you fly away unloading the chunk with piston and the fly back to it and console spam with that error and it cause ghost block
> 
> When set the spawnchunk back to default 2 (i think) this problem havent happen again.
> 
> 

I have tested but it is still happening when using the default gamerules

**Comment by LuckyODO** [comment]
It happened to me, too.

**Comment by xuancat0208** [comment]
After all this time, I've come to a rough correlation—it seems to be related to the number of players and their locations.
For a long time, I've been trying to reproduce this bug on a local server. Previously, it was only a probabilistic event on the server, so it was difficult to gather information.
But recently, a coordinate appeared on the server where this issue occurs 100% of the time, without any reason—it's always 100%.
It's almost certain that as long as that chunk is loaded, ghost pistons will appear.
I thought I had found the decisive key factor, until I perfectly replicated the chunk data to my local server.
Everything worked fine... I tried to reproduce the bug locally and then report it. But I failed. Does anyone have any ideas?

**Comment by MrHua269** [comment]
> After all this time, I've come to a rough correlation—it seems to be related to the number of players and their locations.
> For a long time, I've been trying to reproduce this bug on a local server. Previously, it was only a probabilistic event on the server, so it was difficult to gather information.
> But recently, a coordinate appeared on the server where this issue occurs 100% of the time, without any reason—it's always 100%.
> It's almost certain that as long as that chunk is loaded, ghost pistons will appear.
> I thought I had found the decisive key factor, until I perfectly replicated the chunk data to my local server.
> Everything worked fine... I tried to reproduce the bug locally and then report it. But I failed. Does anyone have any ideas?

I have a fix but it's not really fix that(Just simply reverted a bug fix of mojang in 1.21.2)
I think this issue is caused by something of the chunk system which downgraded the chunk ticket level earlier than vanilla and caused that issue

**Comment by MrHua269** [comment]
> After all this time, I've come to a rough correlation—it seems to be related to the number of players and their locations.
> For a long time, I've been trying to reproduce this bug on a local server. Previously, it was only a probabilistic event on the server, so it was difficult to gather information.
> But recently, a coordinate appeared on the server where this issue occurs 100% of the time, without any reason—it's always 100%.
> It's almost certain that as long as that chunk is loaded, ghost pistons will appear.
> I thought I had found the decisive key factor, until I perfectly replicated the chunk data to my local server.
> Everything worked fine... I tried to reproduce the bug locally and then report it. But I failed. Does anyone have any ideas?

You could see #311

**Comment by MrHua269** [comment]
> > After all this time, I've come to a rough correlation—it seems to be related to the number of players and their locations.
> > For a long time, I've been trying to reproduce this bug on a local server. Previously, it was only a probabilistic event on the server, so it was difficult to gather information.
> > But recently, a coordinate appeared on the server where this issue occurs 100% of the time, without any reason—it's always 100%.
> > It's almost certain that as long as that chunk is loaded, ghost pistons will appear.
> > I thought I had found the decisive key factor, until I perfectly replicated the chunk data to my local server.
> > Everything worked fine... I tried to reproduce the bug locally and then report it. But I failed. Does anyone have any ideas?
> 
> You could see #311

There have been given a stable way to reproduce that bug

**Comment by xuancat0208** [comment]
> > > After all this time, I've come to a rough correlation—it seems to be related to the number of players and their locations.
> > > For a long time, I've been trying to reproduce this bug on a local server. Previously, it was only a probabilistic event on the server, so it was difficult to gather information.
> > > But recently, a coordinate appeared on the server where this issue occurs 100% of the time, without any reason—it's always 100%.
> > > It's almost certain that as long as that chunk is loaded, ghost pistons will appear.
> > > I thought I had found the decisive key factor, until I perfectly replicated the chunk data to my local server.
> > > Everything worked fine... I tried to reproduce the bug locally and then report it. But I failed. Does anyone have any ideas?
> > 
> > 
> > You could see [#311](https://github.com/PaperMC/Folia/issues/311)
> 
> There have been given a stable way to reproduce that bug

It looks like all the reasons can be explained with [#311](https://github.com/PaperMC/Folia/issues/311)

**Comment by Spottedleaf** [comment]
Should be fixed by https://github.com/PaperMC/Folia/commit/d4cf71c327956e374a1e379535f9c47fb0ffc94a
