### ISSUE TITLE
Time Command Exception

### ISSUE THREAD

**Issue by Deichor** [PaperMC/Folia#306]
### Expected behavior

```
[14:11:12 ERROR]: Command exception: /time set 9
java.lang.IllegalStateException: World mismatch: expected world_nether but got world
        at net.minecraft.world.level.Level.getCurrentWorldData(Level.java:841) ~[folia-1.21.4.jar:1.21.4-DEV-d4bc338]
        at net.minecraft.world.level.Level.getGameTime(Level.java:1844) ~[folia-1.21.4.jar:1.21.4-DEV-d4bc338]
        at net.minecraft.server.MinecraftServer.synchronizeTime(MinecraftServer.java:2033) ~[folia-1.21.4.jar:1.21.4-DEV-d4bc338]
        at net.minecraft.server.MinecraftServer.forceTimeSynchronization(MinecraftServer.java:2045) ~[folia-1.21.4.jar:1.21.4-DEV-d4bc338]
        at net.minecraft.server.commands.TimeCommand.setTime(TimeCommand.java:72) ~[folia-1.21.4.jar:1.21.4-DEV-d4bc338]
        at net.minecraft.server.commands.TimeCommand.lambda$register$5(TimeCommand.java:32) ~[folia-1.21.4.jar:1.21.4-DEV-d4bc338]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.3.10.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[folia-1.21.4.jar:1.21.4-DEV-d4bc338]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[folia-1.21.4.jar:1.21.4-DEV-d4bc338]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[folia-1.21.4.jar:1.21.4-DEV-d4bc338]
        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[folia-1.21.4.jar:1.21.4-DEV-d4bc338]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[folia-1.21.4.jar:1.21.4-DEV-d4bc338]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:448) ~[folia-1.21.4.jar:1.21.4-DEV-d4bc338]
        at net.minecraft.commands.Commands.performCommand(Commands.java:355) ~[folia-1.21.4.jar:1.21.4-DEV-d4bc338]
        at net.minecraft.commands.Commands.performCommand(Commands.java:342) ~[folia-1.21.4.jar:1.21.4-DEV-d4bc338]
        at net.minecraft.commands.Commands.performCommand(Commands.java:337) ~[folia-1.21.4.jar:1.21.4-DEV-d4bc338]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2355) ~[folia-1.21.4.jar:1.21.4-DEV-d4bc338]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2329) ~[folia-1.21.4.jar:1.21.4-DEV-d4bc338]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$tryHandleChat$17(ServerGamePacketListenerImpl.java:2501) ~[folia-1.21.4.jar:1.21.4-DEV-d4bc338]
        at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:181) ~[folia-1.21.4.jar:1.21.4-DEV-d4bc338]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1796) ~[folia-1.21.4.jar:1.21.4-DEV-d4bc338]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:407) ~[folia-1.21.4.jar:1.21.4-DEV-d4bc338]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:418) ~[folia-1.21.4.jar:1.21.4-DEV-d4bc338]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:546) ~[concurrentutil-0.0.2.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
>
```

### Observed/Actual behavior

I'm using the /time set command, the time changes, but I get an error in the console.

### Steps/models to reproduce

Use time command

### Plugin and Datapack List

There is no datapack

### Folia version

This server is running Folia version 1.21.4-DEV-dev/1.21.4@d4bc338 (2024-12-06T16:35:23Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.1-DEV-5833269 (MC: 1.21.1)

**Comment by Spottedleaf** [comment]
Resolved in https://github.com/PaperMC/Folia/commit/d8bef962a82402e42ce2be061a37e3cff826eaa4
