### ISSUE TITLE
Folia1.21.4 When the piston pushes the block in front and there is a lot of creatures in the block in front, will produce moving pistons that cannot be cleared normally

### ISSUE THREAD

**Issue by mangocraft** [PaperMC/Folia#311]
### Expected behavior

Piston normal operation

### Observed/Actual behavior

The console will generate the following error:
[13:28:48 ERROR]: [ca.spottedleaf.moonrise.common.util.TickThread] Thread Region Scheduler Thread #1 failed main thread check: Cannot asynchronously load chunks
java.lang.Throwable: null
        at ca.spottedleaf.moonrise.common.util.TickThread.ensureTickThread(TickThread.java:51) ~[luminol-1.21.4.jar:1.21.4-DEV-27a2e2a]
        at net.minecraft.server.level.ServerChunkCache.syncLoad(ServerChunkCache.java:100) ~[luminol-1.21.4.jar:1.21.4-DEV-27a2e2a]
        at net.minecraft.server.level.ServerChunkCache.getChunkFallback(ServerChunkCache.java:153) ~[luminol-1.21.4.jar:1.21.4-DEV-27a2e2a]
        at net.minecraft.server.level.ServerChunkCache.getChunk(ServerChunkCache.java:296) ~[luminol-1.21.4.jar:1.21.4-DEV-27a2e2a]
        at net.minecraft.world.level.Level.getChunk(Level.java:1095) ~[luminol-1.21.4.jar:1.21.4-DEV-27a2e2a]
        at net.minecraft.world.level.Level.getBlockState(Level.java:1396) ~[luminol-1.21.4.jar:1.21.4-DEV-27a2e2a]
        at net.minecraft.world.entity.Entity.checkInsideBlocks(Entity.java:1806) ~[luminol-1.21.4.jar:1.21.4-DEV-27a2e2a]
        at net.minecraft.world.entity.Entity.applyEffectsFromBlocks(Entity.java:1420) ~[luminol-1.21.4.jar:1.21.4-DEV-27a2e2a]
        at net.minecraft.world.entity.Entity.applyEffectsFromBlocks(Entity.java:1404) ~[luminol-1.21.4.jar:1.21.4-DEV-27a2e2a]
        at net.minecraft.world.level.block.piston.PistonMovingBlockEntity.moveEntityByPiston(PistonMovingBlockEntity.java:206) ~[luminol-1.21.4.jar:1.21.4-DEV-27a2e2a]
        at net.minecraft.world.level.block.piston.PistonMovingBlockEntity.moveCollidedEntities(PistonMovingBlockEntity.java:186) ~[luminol-1.21.4.jar:1.21.4-DEV-27a2e2a]
        at net.minecraft.world.level.block.piston.PistonMovingBlockEntity.tick(PistonMovingBlockEntity.java:339) ~[luminol-1.21.4.jar:1.21.4-DEV-27a2e2a]
        at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.tick(LevelChunk.java:1094) ~[luminol-1.21.4.jar:1.21.4-DEV-27a2e2a]
        at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.tick(LevelChunk.java:1036) ~[luminol-1.21.4.jar:1.21.4-DEV-27a2e2a]
        at net.minecraft.world.level.Level.tickBlockEntities(Level.java:1521) ~[luminol-1.21.4.jar:1.21.4-DEV-27a2e2a]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:855) ~[luminol-1.21.4.jar:1.21.4-DEV-27a2e2a]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:2021) ~[luminol-1.21.4.jar:1.21.4-DEV-27a2e2a]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1829) ~[luminol-1.21.4.jar:1.21.4-DEV-27a2e2a]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:407) ~[luminol-1.21.4.jar:1.21.4-DEV-27a2e2a]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:418) ~[luminol-1.21.4.jar:1.21.4-DEV-27a2e2a]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:546) ~[concurrentutil-0.0.2.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[13:28:48 ERROR]: BlockEntity threw exception at world:-571,93,9213
java.lang.IllegalStateException: Cannot asynchronously load chunks
        at ca.spottedleaf.moonrise.common.util.TickThread.ensureTickThread(TickThread.java:52) ~[luminol-1.21.4.jar:1.21.4-DEV-27a2e2a]
        at net.minecraft.server.level.ServerChunkCache.syncLoad(ServerChunkCache.java:100) ~[luminol-1.21.4.jar:1.21.4-DEV-27a2e2a]
        at net.minecraft.server.level.ServerChunkCache.getChunkFallback(ServerChunkCache.java:153) ~[luminol-1.21.4.jar:1.21.4-DEV-27a2e2a]
        at net.minecraft.server.level.ServerChunkCache.getChunk(ServerChunkCache.java:296) ~[luminol-1.21.4.jar:1.21.4-DEV-27a2e2a]
        at net.minecraft.world.level.Level.getChunk(Level.java:1095) ~[luminol-1.21.4.jar:1.21.4-DEV-27a2e2a]
        at net.minecraft.world.level.Level.getBlockState(Level.java:1396) ~[luminol-1.21.4.jar:1.21.4-DEV-27a2e2a]
        at net.minecraft.world.entity.Entity.checkInsideBlocks(Entity.java:1806) ~[luminol-1.21.4.jar:1.21.4-DEV-27a2e2a]
        at net.minecraft.world.entity.Entity.applyEffectsFromBlocks(Entity.java:1420) ~[luminol-1.21.4.jar:1.21.4-DEV-27a2e2a]
        at net.minecraft.world.entity.Entity.applyEffectsFromBlocks(Entity.java:1404) ~[luminol-1.21.4.jar:1.21.4-DEV-27a2e2a]
        at net.minecraft.world.level.block.piston.PistonMovingBlockEntity.moveEntityByPiston(PistonMovingBlockEntity.java:206) ~[luminol-1.21.4.jar:1.21.4-DEV-27a2e2a]
        at net.minecraft.world.level.block.piston.PistonMovingBlockEntity.moveCollidedEntities(PistonMovingBlockEntity.java:186) ~[luminol-1.21.4.jar:1.21.4-DEV-27a2e2a]
        at net.minecraft.world.level.block.piston.PistonMovingBlockEntity.tick(PistonMovingBlockEntity.java:339) ~[luminol-1.21.4.jar:1.21.4-DEV-27a2e2a]
        at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.tick(LevelChunk.java:1094) ~[luminol-1.21.4.jar:1.21.4-DEV-27a2e2a]
        at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.tick(LevelChunk.java:1036) ~[luminol-1.21.4.jar:1.21.4-DEV-27a2e2a]
        at net.minecraft.world.level.Level.tickBlockEntities(Level.java:1521) ~[luminol-1.21.4.jar:1.21.4-DEV-27a2e2a]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:855) ~[luminol-1.21.4.jar:1.21.4-DEV-27a2e2a]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:2021) ~[luminol-1.21.4.jar:1.21.4-DEV-27a2e2a]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1829) ~[luminol-1.21.4.jar:1.21.4-DEV-27a2e2a]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:407) ~[luminol-1.21.4.jar:1.21.4-DEV-27a2e2a]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:418) ~[luminol-1.21.4.jar:1.21.4-DEV-27a2e2a]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:546) ~[concurrentutil-0.0.2.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

Then produce 'moving piston' that cannot be cleared normally：
![Image](https://github.com/user-attachments/assets/b794b18e-834a-4b55-bace-ae4b9c14c43a)

### Steps/models to reproduce

When the piston pushes the block in front and there is a creature in the block in front, will produce 'moving piston' that cannot be cleared normally

### Plugin and Datapack List

[22:51:34 INFO]: - HuskHomes, HuskSync,
[22:51:34 INFO]: - BetterRTP Chunky, CMILib
Essentials, EssentialsSpawn, GSit, LuckPerms, PAPIProxyBridge, PlaceholderAPI
PlayerChat, PlayerTitle, ProtocolLib, QuickShop-Hikari, Residence, Vault, WorldEdit

### Folia version

Folia(Luminol is a fork of Folia):
This server is running Luminol version 1.21.4-DEV-dev/1.21.4@27a2e2a (2024-12-15T07:38:57Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)

**Comment by ColdeZhang** [comment]
same #312

**Comment by mangocraft** [comment]
https://github.com/user-attachments/assets/b49af2d6-a974-453f-8cb3-ff4ff42ce0cb

**Comment by Euphillya** [comment]
You use Luminol, try to reproduce on Folia

**Comment by mangocraft** [comment]
After testing, it is reproduced in the latest version of folia




------------------ Original ------------------
From: Euphyllia ***@***.***&gt;
Date: Mon,Dec 16,2024 5:05 PM
To: PaperMC/Folia ***@***.***&gt;
Cc: YIIYI ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [PaperMC/Folia] Folia1.21.4 When the piston pushes the block infront and there is a lot of creatures in the block in front, will producemoving pistons that cannot be cleared normally (Issue #311)





 
You use Luminol, try to reproduce on Folia

**Comment by Intybyte** [comment]
can't reproduce without plugins

**Comment by mangocraft** [comment]
> can't reproduce without plugins

After I uninstalled all the plugins, I can still reproduce this bug

**Comment by Skullians** [comment]
> After testing, it is reproduced in the latest version of folia
> […](#)
> ------------------ Original ------------------ From: Euphyllia ***@***.***&gt; Date: Mon,Dec 16,2024 5:05 PM To: PaperMC/Folia ***@***.***&gt; Cc: YIIYI ***@***.***&gt;, Author ***@***.***&gt; Subject: Re: [PaperMC/Folia] Folia1.21.4 When the piston pushes the block infront and there is a lot of creatures in the block in front, will producemoving pistons that cannot be cleared normally (Issue [#311](https://github.com/PaperMC/Folia/issues/311)) You use Luminol, try to reproduce on Folia — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

Is this with default configs?

**Comment by mangocraft** [comment]
> > After testing, it is reproduced in the latest version of folia
> > […](#)
> > ------------------ Original ------------------ From: Euphyllia _**@**_._**> Date: Mon,Dec 16,2024 5:05 PM To: PaperMC/Folia _**@**_.**_> Cc: YIIYI _**@**_._**>, Author _**@**_.**_> Subject: Re: [PaperMC/Folia] Folia1.21.4 When the piston pushes the block infront and there is a lot of creatures in the block in front, will producemoving pistons that cannot be cleared normally (Issue [#311](https://github.com/PaperMC/Folia/issues/311)) You use Luminol, try to reproduce on Folia — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _**@**_.***>
> 
> Is this with default configs?

I tested the default config and was able to reproduce the bug.

**Comment by ColdeZhang** [comment]
Iis there any further progress about this ?

**Comment by MrHua269** [comment]
https://github.com/user-attachments/assets/80a209cf-089e-4932-b56c-b4efc09e981f
![Image](https://github.com/user-attachments/assets/22fa7a78-a69e-43ea-9036-15e1d253e454)

**Comment by MrHua269** [comment]
> https://github.com/user-attachments/assets/80a209cf-089e-4932-b56c-b4efc09e981f ![Image](https://github.com/user-attachments/assets/22fa7a78-a69e-43ea-9036-15e1d253e454)

Might be a issue of the chunk system.The entity's chunk status turned TRACKED when the machine is out of the player's simulation distance like that video and entity won't be ticked once before the moving piston block push it and the oldposition is still 0,0,0.
![Image](https://github.com/user-attachments/assets/d871294f-50ee-44ef-8895-a81c9dca54ea)

**Comment by MrHua269** [comment]
Any updates of this issue?()

**Comment by Spottedleaf** [comment]
Duplicate of https://github.com/PaperMC/Folia/issues/302
