### ISSUE TITLE
Using Spectator Mode player navigation menu will crash the server.

### ISSUE THREAD

**Issue by Tudorhc5** [PaperMC/Folia#314]
### Expected behavior

In spectator mode, the hotbar transforms to a menu, which lets you navigate between players on the server, and teleport to them.

In the tested use-case: Spectator is in Nether, Player "To Be Spectated" is in overworld.

When using this menu, you just expect to get teleported to that player, including a smooth dimension switch.

### Observed/Actual behavior

When trying to use the spectator mode menu, to teleport to a player that is in another dimension, the server crashes.

[Click me for error log](https://paste.helpch.at/juwefuhufu.php)
[Click me for complete server logg](https://mclo.gs/Gh9bGww#L1538)

### Steps/models to reproduce

1. Req: Server, 2-3 people 
2. Be in a different dimension than the player you want to teleport to. Have 1 player in a different dimension
3. Set you game-mode to spectator
4. *OPTIONAL*  have a player in the same dimension with you, and spectate him normally, clicking on his character.
5. Try to teleport to the player in the different dimension using spectator mode navigation menu.

### Plugin and Datapack List

```
[12:10:36 INFO]: Server Plugins (64):
[12:10:36 INFO]: Paper Plugins:
[12:10:36 INFO]:  - CrazyCrates, FancyNpcs, TempFly
[12:10:36 INFO]: Bukkit Plugins:
[12:10:36 INFO]:  - AntiPopup, AxAFKZone, AxAuctions, AxEnvoy, AxInventoryRestore, AxPlayerWarps, AxShulkers, AxVaults, BetterGUI, BlueMap
[12:10:36 INFO]:  BlueMapPlayerControl, BungeeGuard, ChestShop, CMI, CMIEInjector, CMILib, CommandBlocker, CommandWhitelist, CoreProtect, Craftorithm
[12:10:36 INFO]:  CustomAnvil, DiscordSRV, EternalTags, fairy-lib-plugin, FurnitureLib, GrimAC, HeadDatabase, InteractiveBoard, JPremium, Lands
[12:10:36 INFO]:  LeaderOS, LiteBans, LuckPerms, Mclogs, mcMMO, McmmoGuiV2, packetevents, PlaceholderAPI, Plan, PlayerCrasher
[12:10:36 INFO]:  PlayerViewDistanceController, PrimeSeller, Protect, ProtocolLib, raytraced-antixray, raytraced-entity-culling, raytraced-tile-culling, SafariNet, SuperHarvest, TAB
[12:10:36 INFO]:  ToolStats, TradeMe, Vault, ViaBackwards, ViaRewind, ViaVersion, voicechat, VotingPlugin, WorldEdit, WorldGuard
[12:10:36 INFO]:  WorldGuardExtraFlags
```

No datapacks.

### Folia version

```
[12:11:18 INFO]: This server is running Folia version 1.21.4-DEV-master@8af1aef (2024-12-25T16:24:53Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)
You are running the latest version
```

### Other

Who knows, maybe I'm an idiot.

**Comment by Runkang10** [comment]
Maybe is because of Paper Teleport API is broken on Folia... I don't know.

**Comment by Tudorhc5** [comment]
> Maybe is because of Paper Teleport API is broken on Folia... I don't know.

I know many parts of the API are broken, but as far as I can tell its a **bug** and not a **feature**. A piece of advice would be: If you have nothing useful to add or contribute, maybe abstain from saying something useless or obvious @Runkang10 
I see Stabrinai mentioned #173 as its the same problem or similar, I saw that is closed now so this should stay open IMO.

If I can help with further testing please feel free to reach out to me
discord: tudorhc5
or contact me at tudor@hc5.ro

**Comment by RitaSister** [comment]
```
at CrazyCrates-4.3.4.jar/com.badbones69.crazycrates.api.ChestManager.closeChest(ChestManager.java:37) ~[CrazyCrates-4.3.4.jar:?]
	at CrazyCrates-4.3.4.jar/com.badbones69.crazycrates.tasks.crates.CrateManager.endQuickCrate(CrateManager.java:1449) ~[CrazyCrates-4.3.4.jar:?]
	at CrazyCrates-4.3.4.jar/com.badbones69.crazycrates.listeners.MiscListener.onPlayerQuit(MiscListener.java:126) ~[CrazyCrates-4.3.4.jar:?]
```
55-57 lines string says what is this cause of plugin.

**Comment by Spottedleaf** [comment]
Should be resolved by https://github.com/PaperMC/Folia/commit/ec78da5ae013799d811d4ce96d960f0fe594ca7c
