### ISSUE TITLE
Reload command crashes server!

### ISSUE THREAD

**Issue by SlayorPlayz** [PaperMC/Folia#44]
### Stack trace

https://paste.gg/p/anonymous/46efd4d5148540fcb288d3aae241865c

### Plugin and Datapack List

Chunky, Grim AC, Better Economy, Folia Vault

### Actions to reproduce (if known)

do /rl confirm

### Folia version

[19:55:41 INFO]: This server is running Folia version git-Folia-"41c5548" (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 41c5548)

### Other

/spigot reload - Doesnt crash the server

**Comment by SlayorPlayz** [comment]
org.bukkit.command.CommandException: Unhandled exception executing 'rl confirm' in org.bukkit.command.defaults.ReloadCommand(reload)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165) ~[folia-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchCommand(CraftServer.java:1017) ~[folia-1.19.4.jar:git-Folia-"41c5548"]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchServerCommand(CraftServer.java:948) ~[folia-1.19.4.jar:git-Folia-"41c5548"]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:501) ~[folia-1.19.4.jar:git-Folia-"41c5548"]
        at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:197) ~[folia-1.19.4.jar:git-Folia-"41c5548"]
        at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:149) ~[folia-1.19.4.jar:git-Folia-"41c5548"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[folia-1.19.4.jar:git-Folia-"41c5548"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.19.4.jar:git-Folia-"41c5548"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.UnsupportedOperationException
        at net.minecraft.server.MinecraftServer.execute(MinecraftServer.java:323) ~[folia-1.19.4.jar:git-Folia-"41c5548"]
        at java.util.concurrent.CompletableFuture.asyncSupplyStage(CompletableFuture.java:1782) ~[?:?]
        at java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java:2005) ~[?:?]
        at net.minecraft.server.MinecraftServer.reloadResources(MinecraftServer.java:2203) ~[folia-1.19.4.jar:git-Folia-"41c5548"]
        at net.minecraft.server.commands.ReloadCommand.reload(ReloadCommand.java:53) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.reloadData(CraftServer.java:1163) ~[folia-1.19.4.jar:git-Folia-"41c5548"]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.reload(CraftServer.java:1097) ~[folia-1.19.4.jar:git-Folia-"41c5548"]
        at org.bukkit.Bukkit.reload(Bukkit.java:930) ~[folia-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54) ~[folia-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[folia-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        ... 8 more

**Comment by kugge** [comment]
This command should be removed, especially in Folia

**Comment by Machine-Maker** [comment]
The issue probably also occurs with the `minecraft:reload` command. So if you just wanted to remove it, you'd want to remove both.

**Comment by Feniksovich** [comment]
> The issue probably also occurs with the `minecraft:reload` command. So if you just wanted to remove it, you'd want to remove both.

Will there be a replacement for it with the same behaviour (datapacks reloading)?

**Comment by Spottedleaf** [comment]
Yeah I don't foresee reload being able to be implemented anytime.
