### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by masmc05** [PaperMC/Folia#47]
### Stack trace

```
paste your stack trace or a paste.gg link here!
```
```
[10:56:49 ERROR]: [ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadPool] Exception thrown from thread 'Tuinity Chunk System Worker #0' in queue 'ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadPool$PrioritisedPoolExecutorImpl@7a1415e7'
net.minecraft.world.level.chunk.MissingPaletteEntryException: Missing Palette entry for index 9.
        at net.minecraft.world.level.chunk.LinearPalette.valueFor(LinearPalette.java:76) ~[?:?]
        at net.minecraft.world.level.chunk.PalettedContainer.get(PalettedContainer.java:208) ~[?:?]
        at ca.spottedleaf.starlight.common.light.StarLightEngine.getBlockState(StarLightEngine.java:297) ~[folia-1.19.4.jar:git-Folia-"41c5548"]
        at ca.spottedleaf.starlight.common.light.StarLightEngine.performLightDecrease(StarLightEngine.java:1333) ~[folia-1.19.4.jar:git-Folia-"41c5548"]
        at ca.spottedleaf.starlight.common.light.BlockStarLightEngine.propagateBlockChanges(BlockStarLightEngine.java:201) ~[folia-1.19.4.jar:git-Folia-"41c5548"]
        at ca.spottedleaf.starlight.common.light.StarLightEngine.blocksChangedInChunk(StarLightEngine.java:427) ~[folia-1.19.4.jar:git-Folia-"41c5548"]
        at io.papermc.paper.chunk.system.light.LightQueue$ChunkTasks.run(LightQueue.java:265) ~[folia-1.19.4.jar:git-Folia-"41c5548"]
        at io.papermc.paper.chunk.system.scheduling.queue.RadiusAwarePrioritisedExecutor$Task.run(RadiusAwarePrioritisedExecutor.java:468) ~[folia-1.19.4.jar:git-Folia-"41c5548"]
        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue$PrioritisedTask.executeInternal(PrioritisedThreadedTaskQueue.java:351) ~[folia-1.19.4.jar:git-Folia-"41c5548"]
        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue.executeTask(PrioritisedThreadedTaskQueue.java:118) ~[folia-1.19.4.jar:git-Folia-"41c5548"]
        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadPool$PrioritisedThread.pollTasks(PrioritisedThreadPool.java:278) ~[folia-1.19.4.jar:git-Folia-"41c5548"]
        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedQueueExecutorThread.run(PrioritisedQueueExecutorThread.java:62) ~[folia-1.19.4.jar:git-Folia-"41c5548"]
```

### Plugin and Datapack List

[10:57:57 INFO]: Paper Plugins:
[10:57:57 INFO]:  - MiniScoreBoard
[10:57:57 INFO]: Bukkit Plugins:
[10:57:57 INFO]:  - Chatty, Chunky, CoreProtect, floodgate, FreedomChat, LuckPerms, spark, TAB, Vault, ViaBackwards
[10:57:57 INFO]:  ViaVersion

### Actions to reproduce (if known)

idk

### Folia version

[10:58:25 INFO]: This server is running Folia version git-Folia-"41c5548" (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 41c5548)
You are running the latest version

**Comment by Spottedleaf** [comment]
This is an issue with how the block data is maintained per section in Vanilla. I _could_ fix it, at the risk of breaking the block storage or causing compatibility issues with plugins. I don't care about the latter, but the former is a very significant issue and so I can't fix this issue.
