### ISSUE TITLE
Lodestone Crashes If Across Regions

### ISSUE THREAD

**Issue by WillQizza** [PaperMC/Folia#60]
### Stack trace

```
[21:55:52] [Region Scheduler Thread #2/ERROR]: Thread Region Scheduler Thread #2 failed main thread check: Accessing poi chunk off-main
java.lang.Throwable: null
	at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:71) ~[folia-1.19.4.jar:git-Folia-"b97116b"]
	at net.minecraft.world.entity.ai.village.poi.PoiManager.d(PoiManager.java:281) ~[?:?]
	at net.minecraft.world.entity.ai.village.poi.PoiManager.exists(PoiManager.java:199) ~[?:?]
	at net.minecraft.world.entity.ai.village.poi.PoiManager.existsAtPosition(PoiManager.java:82) ~[?:?]
	at net.minecraft.world.item.CompassItem.inventoryTick(CompassItem.java:80) ~[?:?]
	at net.minecraft.world.item.ItemStack.inventoryTick(ItemStack.java:768) ~[folia-1.19.4.jar:git-Folia-"b97116b"]
	at net.minecraft.world.entity.player.Inventory.tick(Inventory.java:328) ~[?:?]
	at net.minecraft.world.entity.player.Player.aiStep(Player.java:565) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2978) ~[?:?]
	at net.minecraft.world.entity.player.Player.tick(Player.java:275) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:796) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:388) ~[?:?]
	at net.minecraft.network.Connection.tick(Connection.java:624) ~[?:?]
	at io.papermc.paper.threadedregions.RegionizedWorldData.tickConnections(RegionizedWorldData.java:480) ~[folia-1.19.4.jar:git-Folia-"b97116b"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1537) ~[folia-1.19.4.jar:git-Folia-"b97116b"]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:360) ~[folia-1.19.4.jar:git-Folia-"b97116b"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[folia-1.19.4.jar:git-Folia-"b97116b"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.19.4.jar:git-Folia-"b97116b"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Plugin and Datapack List

No Plugins

### Actions to reproduce (if known)

- Place a lodestone in 1 region
- Create a lodestone compass with it
- Teleport to a different region
- Switch hotbar item to lodestone compass

### Folia version

This server is running Folia version git-Folia-"b97116b" (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: b97116b)
You are running the latest version
Previous version: git-Folia-"17a3236" (MC: 1.19.4)

**Comment by xiaoyueyoqwq** [comment]
yeal, I'm having the same issue too
